-- 00_indexes.sql — indexes, policies and constraints the clone's own setup
-- scripts author for the newer tables. The PostgREST catalog exposes no index
-- information, so these are replayed from bluebellschool/src/api/*.sql and pruned
-- to statements that can only add: CREATE INDEX / POLICY / CONSTRAINT, COMMENT,
-- ENABLE ROW LEVEL SECURITY. Anything destructive or column-altering is
-- dropped from the bundle (01_schema.sql already carries every live column).
-- The surviving statements are executed through bb_try(), which reports and
-- skips failures, so it can be re-run freely. Every statement here needs
-- its table to exist first, so paste it after 01_schema.sql and 02_rls.sql.
-- Generated by tools/gen-schema.mjs — do not hand-edit; re-run the tool.

set search_path = public;

-- ---- guarded execution ----
-- bb_try() runs one statement and only reports a failure, so the order
-- these files are pasted in never matters and a re-run is harmless.
create or replace function bb_try(p_sql text) returns void language plpgsql as $fn$
begin
  execute p_sql;
exception when others then
  raise notice 'bluebell 00_indexes: skipped % (%)', left(p_sql, 70), sqlerrm;
end
$fn$;

-- from src/api/bluebell_cbt_results_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS cbt_results_created_at_idx ON bluebell_cbt_results (created_at DESC)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS cbt_results_student_idx ON bluebell_cbt_results ("studentId")$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_anon_read" ON bluebell_cbt_results$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_authed_read" ON bluebell_cbt_results$q$);
select bb_try($q$CREATE POLICY "cbt_results_anon_read" ON bluebell_cbt_results FOR SELECT TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "cbt_results_authed_read" ON bluebell_cbt_results FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_anon_write" ON bluebell_cbt_results$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_authed_write" ON bluebell_cbt_results$q$);
select bb_try($q$CREATE POLICY "cbt_results_anon_write" ON bluebell_cbt_results FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "cbt_results_authed_write" ON bluebell_cbt_results FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_authed_update" ON bluebell_cbt_results$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_anon_delete" ON bluebell_cbt_results$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_authed_delete" ON bluebell_cbt_results$q$);
select bb_try($q$drop policy if exists "cbt_results_anon_update" on bluebell_cbt_results;
CREATE POLICY "cbt_results_anon_update" ON bluebell_cbt_results FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "cbt_results_authed_update" ON bluebell_cbt_results FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "cbt_results_anon_delete" ON bluebell_cbt_results FOR DELETE TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "cbt_results_authed_delete" ON bluebell_cbt_results FOR DELETE TO authenticated USING (true)$q$);
-- from src/api/bluebell_chat_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS bluebell_chat_messages_conv_idx ON public.bluebell_chat_messages (conversation_id, created_at)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS bluebell_chat_conversations_student_idx ON public.bluebell_chat_conversations (student_id, updated_at DESC)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS bluebell_chat_conversations_teacher_idx ON public.bluebell_chat_conversations (teacher_staff_id, updated_at DESC)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS bluebell_chat_conversations_type_idx ON public.bluebell_chat_conversations (school_type, updated_at DESC)$q$);
-- from src/api/bluebell_chat_rls_fix.sql
select bb_try($q$DROP POLICY IF EXISTS "chat_convo_anon_all" ON public.bluebell_chat_conversations$q$);
select bb_try($q$DROP POLICY IF EXISTS "chat_convo_authed_all" ON public.bluebell_chat_conversations$q$);
select bb_try($q$CREATE POLICY "chat_convo_anon_all" ON public.bluebell_chat_conversations FOR ALL TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "chat_convo_authed_all" ON public.bluebell_chat_conversations FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "chat_msg_anon_all" ON public.bluebell_chat_messages$q$);
select bb_try($q$DROP POLICY IF EXISTS "chat_msg_authed_all" ON public.bluebell_chat_messages$q$);
select bb_try($q$CREATE POLICY "chat_msg_anon_all" ON public.bluebell_chat_messages FOR ALL TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "chat_msg_authed_all" ON public.bluebell_chat_messages FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
-- from src/api/platform_attendance_signout_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_staff_att_signout ON bluebell_staff_attendance(date, check_out_time)$q$);
-- from src/api/platform_attendance_rls_fix.sql
select bb_try($q$ALTER TABLE bluebell_staff_attendance ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$DROP POLICY IF EXISTS "attendance_anon_write" ON bluebell_attendance$q$);
select bb_try($q$DROP POLICY IF EXISTS "attendance_authed_read" ON bluebell_attendance$q$);
select bb_try($q$DROP POLICY IF EXISTS "attendance_authed_write" ON bluebell_attendance$q$);
select bb_try($q$drop policy if exists "attendance_anon_read" on bluebell_attendance;
CREATE POLICY "attendance_anon_read" ON bluebell_attendance FOR SELECT TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "attendance_anon_write" ON bluebell_attendance FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "attendance_authed_read" ON bluebell_attendance FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "attendance_authed_write" ON bluebell_attendance FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "attendance_authed_update" ON bluebell_attendance$q$);
select bb_try($q$drop policy if exists "attendance_anon_update" on bluebell_attendance;
CREATE POLICY "attendance_anon_update" ON bluebell_attendance FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "attendance_authed_update" ON bluebell_attendance FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_attendance_anon_write" ON bluebell_staff_attendance$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_attendance_authed_read" ON bluebell_staff_attendance$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_attendance_authed_write" ON bluebell_staff_attendance$q$);
select bb_try($q$drop policy if exists "staff_attendance_anon_read" on bluebell_staff_attendance;
CREATE POLICY "staff_attendance_anon_read" ON bluebell_staff_attendance FOR SELECT TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_attendance_anon_write" ON bluebell_staff_attendance FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_attendance_authed_read" ON bluebell_staff_attendance FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_attendance_authed_write" ON bluebell_staff_attendance FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_attendance_anon_update" ON bluebell_staff_attendance$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_attendance_authed_update" ON bluebell_staff_attendance$q$);
select bb_try($q$CREATE POLICY "staff_attendance_anon_update" ON bluebell_staff_attendance FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_attendance_authed_update" ON bluebell_staff_attendance FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
-- from src/api/platform_staff_portal_setup.sql
select bb_try($q$CREATE INDEX if not exists idx_bluebell_assignments_class ON bluebell_assignments(class)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_assignments_subject ON bluebell_assignments(subject)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_assignments_due ON bluebell_assignments(due_date)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_notes_class ON bluebell_notes(class)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_notes_subject ON bluebell_notes(subject)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_lesson_plans_class ON bluebell_lesson_plans(class)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_lesson_plans_review ON bluebell_lesson_plans(review_status)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_announcements_audience ON bluebell_announcements(audience)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_announcements_created ON bluebell_announcements(created_at DESC)$q$);
-- from src/api/platform_staff_management_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_staff_email ON bluebell_staff(lower(email))$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_staff_auth_user ON bluebell_staff(auth_user_id)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_staff_assign_staff ON bluebell_staff_assignments(staff_id)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_staff_assign_class ON bluebell_staff_assignments(class)$q$);
-- from src/api/platform_staff_rls_fix.sql
select bb_try($q$ALTER TABLE bluebell_staff_assignments ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_authed_read" ON bluebell_staff$q$);
select bb_try($q$drop policy if exists "staff_anon_read" on bluebell_staff;
CREATE POLICY "staff_anon_read" ON bluebell_staff FOR SELECT TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_authed_read" ON bluebell_staff FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_authed_write" ON bluebell_staff$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_anon_update" ON bluebell_staff$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_authed_update" ON bluebell_staff$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_anon_delete" ON bluebell_staff$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_authed_delete" ON bluebell_staff$q$);
select bb_try($q$drop policy if exists "staff_anon_write" on bluebell_staff;
CREATE POLICY "staff_anon_write" ON bluebell_staff FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_authed_write" ON bluebell_staff FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_anon_update" ON bluebell_staff FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_authed_update" ON bluebell_staff FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_anon_delete" ON bluebell_staff FOR DELETE TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_authed_delete" ON bluebell_staff FOR DELETE TO authenticated USING (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_authed_read" ON bluebell_staff_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_anon_write" ON bluebell_staff_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_authed_write" ON bluebell_staff_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_anon_update" ON bluebell_staff_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_authed_update" ON bluebell_staff_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_anon_delete" ON bluebell_staff_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "staff_assignments_authed_delete" ON bluebell_staff_assignments$q$);
select bb_try($q$drop policy if exists "staff_assignments_anon_read" on bluebell_staff_assignments;
CREATE POLICY "staff_assignments_anon_read" ON bluebell_staff_assignments FOR SELECT TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_authed_read" ON bluebell_staff_assignments FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_anon_write" ON bluebell_staff_assignments FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_authed_write" ON bluebell_staff_assignments FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_anon_update" ON bluebell_staff_assignments FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_authed_update" ON bluebell_staff_assignments FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_anon_delete" ON bluebell_staff_assignments FOR DELETE TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "staff_assignments_authed_delete" ON bluebell_staff_assignments FOR DELETE TO authenticated USING (true)$q$);
-- from src/api/platform_student_portal_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_student_auth_user ON bluebell_student(auth_user_id)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_student_email ON bluebell_student(lower(email))$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_student_token ON bluebell_student(token)$q$);
-- from src/api/platform_academics_rls_fix.sql
select bb_try($q$ALTER TABLE public.bluebell_assignments ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$ALTER TABLE public.bluebell_lesson_plans ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$ALTER TABLE public.bluebell_announcements ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$DROP POLICY IF EXISTS "notes_read" ON public.bluebell_notes$q$);
select bb_try($q$DROP POLICY IF EXISTS "notes_write" ON public.bluebell_notes$q$);
select bb_try($q$DROP POLICY IF EXISTS "assignments_read" ON public.bluebell_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "assignments_write" ON public.bluebell_assignments$q$);
select bb_try($q$DROP POLICY IF EXISTS "lesson_plans_read" ON public.bluebell_lesson_plans$q$);
select bb_try($q$DROP POLICY IF EXISTS "lesson_plans_write" ON public.bluebell_lesson_plans$q$);
select bb_try($q$DROP POLICY IF EXISTS "announcements_read" ON public.bluebell_announcements$q$);
select bb_try($q$DROP POLICY IF EXISTS "announcements_write" ON public.bluebell_announcements$q$);
select bb_try($q$CREATE POLICY "assignments_read" ON public.bluebell_assignments FOR SELECT TO anon, authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "lesson_plans_read" ON public.bluebell_lesson_plans FOR SELECT TO anon, authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "announcements_read" ON public.bluebell_announcements FOR SELECT TO anon, authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "assignments_write" ON public.bluebell_assignments FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "lesson_plans_write" ON public.bluebell_lesson_plans FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "announcements_write" ON public.bluebell_announcements FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$ALTER TABLE public.bluebell_cbt_essay ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_completion_read" ON public.bluebell_cbt_completion$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_completion_write" ON public.bluebell_cbt_completion$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_essay_read" ON public.bluebell_cbt_essay$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_essay_write" ON public.bluebell_cbt_essay$q$);
select bb_try($q$CREATE POLICY "cbt_completion_read" ON public.bluebell_cbt_completion FOR SELECT TO anon, authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "cbt_essay_read" ON public.bluebell_cbt_essay FOR SELECT TO anon, authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "cbt_completion_write" ON public.bluebell_cbt_completion FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "cbt_essay_write" ON public.bluebell_cbt_essay FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "auditlogs_read" ON public.bluebell_auditlogs$q$);
select bb_try($q$DROP POLICY IF EXISTS "auditlogs_write" ON public.bluebell_auditlogs$q$);
select bb_try($q$CREATE POLICY "auditlogs_read" ON public.bluebell_auditlogs FOR SELECT TO authenticated USING (true)$q$);
-- from src/api/platform_result_history_rls_fix.sql
select bb_try($q$DROP POLICY IF EXISTS "result_history_authed_read" ON bluebell_result_history$q$);
select bb_try($q$drop policy if exists "result_history_anon_read" on bluebell_result_history;
CREATE POLICY "result_history_anon_read" ON bluebell_result_history FOR SELECT TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "result_history_authed_read" ON bluebell_result_history FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "result_history_authed_write" ON bluebell_result_history$q$);
select bb_try($q$drop policy if exists "result_history_anon_write" on bluebell_result_history;
CREATE POLICY "result_history_anon_write" ON bluebell_result_history FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "result_history_authed_write" ON bluebell_result_history FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "result_history_authed_update" ON bluebell_result_history$q$);
select bb_try($q$DROP POLICY IF EXISTS "result_history_anon_delete" ON bluebell_result_history$q$);
select bb_try($q$DROP POLICY IF EXISTS "result_history_authed_delete" ON bluebell_result_history$q$);
select bb_try($q$drop policy if exists "result_history_anon_update" on bluebell_result_history;
CREATE POLICY "result_history_anon_update" ON bluebell_result_history FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "result_history_authed_update" ON bluebell_result_history FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "result_history_anon_delete" ON bluebell_result_history FOR DELETE TO anon USING (true)$q$);
select bb_try($q$CREATE POLICY "result_history_authed_delete" ON bluebell_result_history FOR DELETE TO authenticated USING (true)$q$);
-- from src/api/platform_website_enquiries_setup.sql
select bb_try($q$CREATE INDEX if not exists idx_bluebell_enquiries_status ON bluebell_enquiries(status)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_enquiries_email ON bluebell_enquiries(lower(email))$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_enquiries_created ON bluebell_enquiries(created_at DESC)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_admissions_status ON bluebell_admissions_applications(status)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_admissions_email ON bluebell_admissions_applications(lower(parent_email))$q$);
-- from src/api/platform_website_rls_fix.sql
select bb_try($q$ALTER TABLE bluebell_admissions_applications ENABLE ROW LEVEL SECURITY$q$);
select bb_try($q$drop policy if exists "enquiries_anon_insert" on bluebell_enquiries;
CREATE POLICY "enquiries_anon_insert" ON bluebell_enquiries FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "enquiries_authed_insert" ON bluebell_enquiries$q$);
select bb_try($q$DROP POLICY IF EXISTS "enquiries_authed_update" ON bluebell_enquiries$q$);
select bb_try($q$DROP POLICY IF EXISTS "enquiries_authed_delete" ON bluebell_enquiries$q$);
select bb_try($q$drop policy if exists "enquiries_authed_read" on bluebell_enquiries;
CREATE POLICY "enquiries_authed_read" ON bluebell_enquiries FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "enquiries_authed_insert" ON bluebell_enquiries FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "enquiries_authed_update" ON bluebell_enquiries FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "enquiries_authed_delete" ON bluebell_enquiries FOR DELETE TO authenticated USING (true)$q$);
select bb_try($q$drop policy if exists "admissions_anon_insert" on bluebell_admissions_applications;
CREATE POLICY "admissions_anon_insert" ON bluebell_admissions_applications FOR INSERT TO anon WITH CHECK (true)$q$);
select bb_try($q$DROP POLICY IF EXISTS "admissions_authed_insert" ON bluebell_admissions_applications$q$);
select bb_try($q$DROP POLICY IF EXISTS "admissions_authed_update" ON bluebell_admissions_applications$q$);
select bb_try($q$DROP POLICY IF EXISTS "admissions_authed_delete" ON bluebell_admissions_applications$q$);
select bb_try($q$drop policy if exists "admissions_authed_read" on bluebell_admissions_applications;
CREATE POLICY "admissions_authed_read" ON bluebell_admissions_applications FOR SELECT TO authenticated USING (true)$q$);
select bb_try($q$CREATE POLICY "admissions_authed_insert" ON bluebell_admissions_applications FOR INSERT TO authenticated WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "admissions_authed_update" ON bluebell_admissions_applications FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "admissions_authed_delete" ON bluebell_admissions_applications FOR DELETE TO authenticated USING (true)$q$);
-- from src/api/bluebell_assignment_submissions_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_submission_assignment ON bluebell_assignment_submissions (assignment_id)$q$);
select bb_try($q$DROP POLICY IF EXISTS "submissions_anon_all" ON bluebell_assignment_submissions$q$);
select bb_try($q$DROP POLICY IF EXISTS "submissions_authed_all" ON bluebell_assignment_submissions$q$);
select bb_try($q$CREATE POLICY "submissions_anon_all" ON bluebell_assignment_submissions FOR ALL TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "submissions_authed_all" ON bluebell_assignment_submissions FOR ALL TO authenticated USING (true) WITH CHECK (true)$q$);
-- from src/api/bluebell_disabled_accounts_setup.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_disabled_email ON bluebell_disabled_accounts(lower(email))$q$);
select bb_try($q$DROP POLICY IF EXISTS "bluebell_disabled_accounts_select" ON bluebell_disabled_accounts$q$);
select bb_try($q$CREATE POLICY "bluebell_disabled_accounts_select" ON bluebell_disabled_accounts FOR SELECT TO anon, authenticated USING (true)$q$);
-- from src/api/bluebell_staff_credentials.sql
select bb_try($q$ALTER TABLE public.bluebell_staff_credentials ENABLE ROW LEVEL SECURITY$q$);
-- from src/api/bluebell_cbt_created_by.sql
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_cbtcompletion_created_by ON public.bluebell_cbt_completion (created_by, class, subject)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_cbtessay_created_by ON public.bluebell_cbt_essay (created_by, class, subject)$q$);
-- from src/api/bluebell_cbt_max_score.sql
select bb_try($q$CREATE UNIQUE INDEX IF NOT EXISTS cbt_results_submission_key ON "bluebell_cbt_results" ("submissionKey") WHERE "submissionKey" IS NOT NULL$q$);
select bb_try($q$DROP POLICY IF EXISTS "cbt_results_anon_read" ON "bluebell_cbt_results"$q$);
select bb_try($q$CREATE POLICY "cbt_results_anon_read" ON "bluebell_cbt_results" FOR SELECT TO anon USING (true)$q$);
-- from src/api/bluebell_student_token_count.sql
select bb_try($q$DROP POLICY IF EXISTS "student_authed_update" ON bluebell_student$q$);
select bb_try($q$drop policy if exists "student_anon_update" on bluebell_student;
CREATE POLICY "student_anon_update" ON bluebell_student FOR UPDATE TO anon USING (true) WITH CHECK (true)$q$);
select bb_try($q$CREATE POLICY "student_authed_update" ON bluebell_student FOR UPDATE TO authenticated USING (true) WITH CHECK (true)$q$);
-- from src/api/feature_expansion_setup.sql
select bb_try($q$CREATE INDEX if not exists idx_bluebell_staff_name ON bluebell_staff(name)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_staff_status ON bluebell_staff(status)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_attendance_date ON bluebell_attendance(date)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_attendance_class ON bluebell_attendance(class)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_attendance_term ON bluebell_attendance(term)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_attendance_name ON bluebell_attendance(student_name)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_staff_att_date ON bluebell_staff_attendance(date)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_staff_att_name ON bluebell_staff_attendance(staff_name)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_auditlogs_created ON bluebell_auditlogs(created_at)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_auditlogs_email ON bluebell_auditlogs(email)$q$);
select bb_try($q$CREATE INDEX if not exists idx_bluebell_auditlogs_action ON bluebell_auditlogs(action)$q$);
select bb_try($q$CREATE INDEX IF NOT EXISTS idx_bluebell_result_history_class ON bluebell_result_history("studentClass")$q$);

drop function bb_try(text);

-- 191 statement(s) kept, 181 pruned as already-applied or non-additive,
-- 6 pruned because their table is not part of Bluebell's provisioned set.
