-- 01_schema.sql — Bluebell International School table structure, the same
-- columns and names as JMIS (jmis_* preserved verbatim; brand.json
-- renameTables=false). Bluebell runs this in its OWN Supabase project.
-- Generated by tools/gen-schema.mjs — do not hand-edit; re-run the tool.
-- Source: the live PostgREST catalog at https://btnatydmfunhwgoeguus.supabase.co (column names, Postgres
-- types, NOT NULL, primary and foreign keys). Additive and idempotent:
-- CREATE TABLE IF NOT EXISTS only, no DROP, no ALTER of existing columns.
-- Paste order: 01 -> 02 -> 00 -> 03 -> 04 (see db/README.md).

set search_path = public;

-- devauth  (4 columns, pk id)
CREATE TABLE IF NOT EXISTS devauth (
  id bigint generated always as identity,
  created_at timestamp with time zone not null,
  email text,
  user_id text,
  PRIMARY KEY (id)
);

-- jmis_admissions_applications  (16 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_admissions_applications (
  id bigint generated always as identity,
  parent_name text not null,
  parent_email text not null,
  parent_phone text,
  parent_address text,
  child_name text not null,
  child_dob text,
  child_sex text,
  applying_class text,
  current_school text,
  special_needs text,
  preferred_visit_date text,
  message text,
  status text not null,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_announcements  (7 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_announcements (
  id bigint generated always as identity,
  title text not null,
  body text not null,
  audience text not null,
  pinned boolean,
  created_by text,
  created_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_assignment_submissions  (11 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_assignment_submissions (
  id bigint generated always as identity,
  assignment_id bigint not null,
  class text not null,
  subject text,
  student_id bigint,
  student_name text not null,
  submission_text text,
  file_url text,
  status text,
  submitted_at timestamp with time zone,
  updated_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_assignments  (12 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_assignments (
  id bigint generated always as identity,
  class text not null,
  subject text not null,
  title text not null,
  instructions text,
  due_date date,
  attachment_url text,
  assignment_type text,
  academic_session text,
  term text,
  created_by text,
  created_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_attendance  (14 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_attendance (
  id bigint generated always as identity,
  student_id bigint,
  student_name text not null,
  class text not null,
  date date not null,
  session text,
  term text,
  check_in_time timestamp with time zone,
  method text,
  created_at timestamp with time zone,
  status text,
  recorded_by text,
  check_out_time timestamp with time zone,
  sign_out_method text,
  PRIMARY KEY (id)
);

-- jmis_auditlogs  (8 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_auditlogs (
  id bigint generated always as identity,
  email text not null,
  role text,
  action text not null,
  target_table text,
  record_id text,
  details jsonb,
  created_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_cbtQuestions  (14 columns, pk id)
CREATE TABLE IF NOT EXISTS "jmis_cbtQuestions" (
  id bigint generated always as identity,
  subject text,
  class text,
  duration integer,
  questions jsonb,
  image text,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  active boolean,
  teacher_id text,
  purpose text,
  term text,
  created_by text,
  "maxScore" numeric,
  PRIMARY KEY (id)
);

-- jmis_cbt_completion  (12 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_cbt_completion (
  id uuid,
  subject text not null,
  class text not null,
  term text,
  duration integer not null,
  purpose text,
  questions jsonb not null,
  image text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  created_by text,
  "maxScore" numeric,
  PRIMARY KEY (id)
);

-- jmis_cbt_essay  (12 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_cbt_essay (
  id uuid,
  subject text not null,
  class text not null,
  term text,
  duration integer not null,
  purpose text,
  questions jsonb not null,
  image text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  created_by text,
  "maxScore" numeric,
  PRIMARY KEY (id)
);

-- jmis_cbt_results  (16 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_cbt_results (
  id bigint generated always as identity,
  "studentId" bigint,
  "studentName" text,
  "studentClass" text,
  score numeric,
  "totalQuestions" integer,
  percentage numeric,
  subject text,
  term text,
  purpose text,
  "sessionType" text,
  answers jsonb,
  "examResults" jsonb,
  created_at timestamp with time zone not null,
  "maxScore" numeric,
  "submissionKey" text,
  PRIMARY KEY (id)
);

-- jmis_chat_conversations  (10 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_chat_conversations (
  id uuid,
  pair_key text not null,
  student_id text not null,
  student_name text not null,
  student_class text not null,
  school_type text not null,
  teacher_staff_id text,
  school_label text not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  PRIMARY KEY (id)
);

-- jmis_chat_messages  (14 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_chat_messages (
  id uuid,
  conversation_id uuid not null,
  sender_side text not null,
  sender_key text not null,
  sender_name text not null,
  body text not null,
  attachment_url text,
  attachment_name text,
  attachment_mime text,
  attachment_size bigint,
  reply_to_id uuid,
  edited_at timestamp with time zone,
  deleted boolean not null,
  created_at timestamp with time zone not null,
  PRIMARY KEY (id)
);

-- jmis_class_specific_fees  (5 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_class_specific_fees (
  id bigint generated always as identity,
  class_name text not null,
  next_term_fees numeric,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  PRIMARY KEY (id)
);

-- jmis_classfees  (63 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_classfees (
  id bigint generated always as identity,
  classname text,
  amount numeric,
  description text,
  creche numeric,
  prenursery numeric,
  nursery1 numeric,
  nursery2 numeric,
  year1 numeric,
  year2 numeric,
  year3 numeric,
  year4 numeric,
  year5 numeric,
  year6 numeric,
  year7 numeric,
  year8 numeric,
  year9 numeric,
  "clubFee" numeric,
  prenurseryuniform text,
  nurseryuniform text,
  yearuniform text,
  partyfee text,
  prenurserytextbook text,
  nursery1textbook text,
  nursery2textbook text,
  year1textbook text,
  year2textbook text,
  year3textbook text,
  year4textbook text,
  year5textbook text,
  year6textbook text,
  year7textbook text,
  year8textbook text,
  year9textbook text,
  prenurseryexercisebook text,
  nurseryexercisebook text,
  yearexercisebook text,
  year6exercisebook text,
  year7exercisebook text,
  year8exercisebook text,
  year9exercisebook text,
  excursionfees text,
  "admissionForm" text,
  "tuitionFee" text,
  "learningResources" text,
  "lessonFee" text,
  "afterSchoolCare" text,
  "busFee" text,
  clubfee numeric,
  admissionform text,
  tuitionfee text,
  learningresources text,
  lessonfee text,
  afterschoolcare text,
  busfee text,
  prenursery1 numeric,
  prenursery2 numeric,
  prenursery1uniform text,
  prenursery2uniform text,
  prenursery1textbook text,
  prenursery2textbook text,
  prenursery1exercisebook text,
  prenursery2exercisebook text,
  PRIMARY KEY (id)
);

-- jmis_disabled_accounts  (7 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_disabled_accounts (
  id uuid,
  email text not null,
  role text not null,
  name text,
  reason text,
  disabled_by text,
  disabled_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_enquiries  (14 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_enquiries (
  id bigint generated always as identity,
  name text not null,
  email text not null,
  phone text,
  enquiry_type text,
  child_age_class text,
  message text,
  status text not null,
  follow_up_notes jsonb,
  next_follow_up date,
  assigned_to text,
  source text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_lesson_plans  (28 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_lesson_plans (
  id bigint generated always as identity,
  class text not null,
  subject text not null,
  academic_session text,
  term text,
  week integer,
  objectives text,
  content text,
  activities text,
  resources text,
  submitted_by text,
  review_status text,
  reviewed_by text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  topic text,
  sub_topic text,
  lesson_no text,
  duration text,
  age text,
  lesson_date text,
  prior_knowledge text,
  possible_problems text,
  evaluation text,
  homework text,
  steps jsonb not null,
  teacher_name text,
  head_teacher text,
  PRIMARY KEY (id)
);

-- jmis_notes  (10 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_notes (
  id bigint generated always as identity,
  class text not null,
  subject text not null,
  title text not null,
  content text,
  file_url text,
  academic_session text,
  term text,
  uploaded_by text,
  created_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_paymentsinfo  (16 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_paymentsinfo (
  id bigint generated always as identity,
  description text,
  currentterm text,
  name text,
  class text,
  sex text,
  invoiceno text,
  date date,
  amountpaid numeric,
  paymentdescription text,
  user_id text,
  transactionid text,
  paymentmethod text,
  status text,
  studentid text,
  receiptimage text,
  PRIMARY KEY (id)
);

-- jmis_result  (14 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_result (
  id bigint generated always as identity,
  "studentId" text,
  "studentName" text,
  "studentClass" text,
  "term1Subjects" jsonb,
  "term2Subjects" jsonb,
  "term3Subjects" jsonb,
  overall1st jsonb,
  overall2nd jsonb,
  overall3rd jsonb,
  token text,
  "uploadResult" boolean,
  "tokenCount" integer,
  uploadmidtermresult boolean,
  PRIMARY KEY (id)
);

-- jmis_result_history  (16 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_result_history (
  id bigint generated always as identity,
  "studentId" text,
  "studentName" text,
  "studentClass" text,
  "term1Subjects" jsonb,
  "term2Subjects" jsonb,
  "term3Subjects" jsonb,
  overall1st jsonb,
  overall2nd jsonb,
  overall3rd jsonb,
  token text,
  "uploadResult" boolean,
  "tokenCount" integer,
  uploadmidtermresult boolean,
  archived_at timestamp with time zone,
  archived_session text,
  PRIMARY KEY (id)
);

-- jmis_secretaryauth  (3 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_secretaryauth (
  id bigint generated always as identity,
  email text not null,
  created_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_settings  (22 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_settings (
  id bigint generated always as identity,
  "cbtPassword" text,
  schoolname text,
  session text,
  term text,
  "nextTermBegins" text,
  "nextTermFees" numeric,
  "schoolOpened" integer,
  "checkResult" date,
  "heroContent" jsonb,
  "facilitiesContent" jsonb,
  "galleryContent" jsonb,
  "testimonialContent" jsonb,
  "aboutContent" jsonb,
  "contactContent" jsonb,
  user_id text,
  "lockResult" boolean,
  "resultLock" boolean,
  "adminEmail" text,
  use_class_specific_fees boolean,
  additionalemails text,
  session_history jsonb,
  PRIMARY KEY (id)
);

-- jmis_staff  (17 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_staff (
  id uuid,
  name text not null,
  role text,
  email text,
  phone text,
  status text,
  created_at timestamp with time zone,
  staff_no text,
  sex text,
  address text,
  class_assigned text,
  designation text,
  subjects text[],
  department text,
  profile_pic text,
  auth_user_id uuid,
  qr_payload text,
  PRIMARY KEY (id)
);

-- jmis_staff_assignments  (7 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_staff_assignments (
  id uuid,
  staff_id uuid not null,
  class text not null,
  subject text,
  assignment_type text not null,
  academic_session text,
  created_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- jmis_staff_attendance  (12 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_staff_attendance (
  id bigint generated always as identity,
  staff_id uuid,
  staff_name text not null,
  role text,
  date date not null,
  session text,
  term text,
  check_in_time timestamp with time zone,
  method text,
  created_at timestamp with time zone,
  check_out_time timestamp with time zone,
  sign_out_method text,
  PRIMARY KEY (id)
);

-- jmis_staff_credentials  (5 columns, pk staff_id)
CREATE TABLE IF NOT EXISTS jmis_staff_credentials (
  staff_id uuid,
  email text,
  password text not null,
  set_at timestamp with time zone,
  set_by text,
  PRIMARY KEY (staff_id)
);

-- jmis_student  (14 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_student (
  id bigint generated always as identity,
  name text not null,
  class text,
  sex text,
  parentcontact text,
  token text,
  passport text,
  user_id text,
  auth_user_id uuid,
  portal_status text,
  email text,
  address text,
  first_login boolean,
  "tokenCount" integer not null,
  PRIMARY KEY (id)
);

-- jmis_teacherauth  (2 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_teacherauth (
  id bigint generated always as identity,
  email text,
  PRIMARY KEY (id)
);

-- jmis_userauth  (2 columns, pk id)
CREATE TABLE IF NOT EXISTS jmis_userauth (
  id bigint generated always as identity,
  email text,
  PRIMARY KEY (id)
);

-- Foreign keys (deferred so table order never matters; NOT VALID keeps
-- this non-destructive for any row already present).
ALTER TABLE jmis_chat_messages DROP CONSTRAINT IF EXISTS jmis_chat_messages_conversation_id_fkey;
ALTER TABLE jmis_chat_messages ADD CONSTRAINT jmis_chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES jmis_chat_conversations (id) NOT VALID;
ALTER TABLE jmis_chat_messages DROP CONSTRAINT IF EXISTS jmis_chat_messages_reply_to_id_fkey;
ALTER TABLE jmis_chat_messages ADD CONSTRAINT jmis_chat_messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES jmis_chat_messages (id) NOT VALID;
ALTER TABLE jmis_staff_assignments DROP CONSTRAINT IF EXISTS jmis_staff_assignments_staff_id_fkey;
ALTER TABLE jmis_staff_assignments ADD CONSTRAINT jmis_staff_assignments_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES jmis_staff (id) NOT VALID;
ALTER TABLE jmis_staff_attendance DROP CONSTRAINT IF EXISTS jmis_staff_attendance_staff_id_fkey;
ALTER TABLE jmis_staff_attendance ADD CONSTRAINT jmis_staff_attendance_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES jmis_staff (id) NOT VALID;
ALTER TABLE jmis_staff_credentials DROP CONSTRAINT IF EXISTS jmis_staff_credentials_staff_id_fkey;
ALTER TABLE jmis_staff_credentials ADD CONSTRAINT jmis_staff_credentials_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES jmis_staff (id) NOT VALID;

-- Done. 31 table(s).
