-- 02_rls.sql — Bluebell's data-access posture.
-- Generated by tools/gen-schema.mjs — do not hand-edit; re-run the tool.
-- The five portals talk to PostgREST with the public anon key (the browser
-- holds no service-role credential), so every provisioned table needs
-- permissive policies for anon + authenticated. This mirrors the posture the
-- repo's own setup scripts use (bluebell_cbt_results_setup.sql,
-- platform_academics_rls_fix.sql). Re-runnable: each policy is dropped first.
--
-- NOTE: this is an open posture by design for a school-internal system where
-- the apps are the only clients. Tighten it per table once Bluebell's real
-- role model is in place — see README.md "Locking the database down".

set search_path = public;

ALTER TABLE devauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS devauth_select_all ON devauth;
CREATE POLICY devauth_select_all ON devauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS devauth_insert_all ON devauth;
CREATE POLICY devauth_insert_all ON devauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS devauth_update_all ON devauth;
CREATE POLICY devauth_update_all ON devauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS devauth_delete_all ON devauth;
CREATE POLICY devauth_delete_all ON devauth FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_admissions_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_admissions_applications_select_all ON bluebell_admissions_applications;
CREATE POLICY bluebell_admissions_applications_select_all ON bluebell_admissions_applications FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_admissions_applications_insert_all ON bluebell_admissions_applications;
CREATE POLICY bluebell_admissions_applications_insert_all ON bluebell_admissions_applications FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_admissions_applications_update_all ON bluebell_admissions_applications;
CREATE POLICY bluebell_admissions_applications_update_all ON bluebell_admissions_applications FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_admissions_applications_delete_all ON bluebell_admissions_applications;
CREATE POLICY bluebell_admissions_applications_delete_all ON bluebell_admissions_applications FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_announcements_select_all ON bluebell_announcements;
CREATE POLICY bluebell_announcements_select_all ON bluebell_announcements FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_announcements_insert_all ON bluebell_announcements;
CREATE POLICY bluebell_announcements_insert_all ON bluebell_announcements FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_announcements_update_all ON bluebell_announcements;
CREATE POLICY bluebell_announcements_update_all ON bluebell_announcements FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_announcements_delete_all ON bluebell_announcements;
CREATE POLICY bluebell_announcements_delete_all ON bluebell_announcements FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_assignment_submissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_assignment_submissions_select_all ON bluebell_assignment_submissions;
CREATE POLICY bluebell_assignment_submissions_select_all ON bluebell_assignment_submissions FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_assignment_submissions_insert_all ON bluebell_assignment_submissions;
CREATE POLICY bluebell_assignment_submissions_insert_all ON bluebell_assignment_submissions FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_assignment_submissions_update_all ON bluebell_assignment_submissions;
CREATE POLICY bluebell_assignment_submissions_update_all ON bluebell_assignment_submissions FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_assignment_submissions_delete_all ON bluebell_assignment_submissions;
CREATE POLICY bluebell_assignment_submissions_delete_all ON bluebell_assignment_submissions FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_assignments_select_all ON bluebell_assignments;
CREATE POLICY bluebell_assignments_select_all ON bluebell_assignments FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_assignments_insert_all ON bluebell_assignments;
CREATE POLICY bluebell_assignments_insert_all ON bluebell_assignments FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_assignments_update_all ON bluebell_assignments;
CREATE POLICY bluebell_assignments_update_all ON bluebell_assignments FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_assignments_delete_all ON bluebell_assignments;
CREATE POLICY bluebell_assignments_delete_all ON bluebell_assignments FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_attendance_select_all ON bluebell_attendance;
CREATE POLICY bluebell_attendance_select_all ON bluebell_attendance FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_attendance_insert_all ON bluebell_attendance;
CREATE POLICY bluebell_attendance_insert_all ON bluebell_attendance FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_attendance_update_all ON bluebell_attendance;
CREATE POLICY bluebell_attendance_update_all ON bluebell_attendance FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_attendance_delete_all ON bluebell_attendance;
CREATE POLICY bluebell_attendance_delete_all ON bluebell_attendance FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_auditlogs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_auditlogs_select_all ON bluebell_auditlogs;
CREATE POLICY bluebell_auditlogs_select_all ON bluebell_auditlogs FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_auditlogs_insert_all ON bluebell_auditlogs;
CREATE POLICY bluebell_auditlogs_insert_all ON bluebell_auditlogs FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_auditlogs_update_all ON bluebell_auditlogs;
CREATE POLICY bluebell_auditlogs_update_all ON bluebell_auditlogs FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_auditlogs_delete_all ON bluebell_auditlogs;
CREATE POLICY bluebell_auditlogs_delete_all ON bluebell_auditlogs FOR DELETE TO anon, authenticated using (true);

ALTER TABLE "bluebell_cbtQuestions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bluebell_cbtQuestions_select_all" ON "bluebell_cbtQuestions";
CREATE POLICY "bluebell_cbtQuestions_select_all" ON "bluebell_cbtQuestions" FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS "bluebell_cbtQuestions_insert_all" ON "bluebell_cbtQuestions";
CREATE POLICY "bluebell_cbtQuestions_insert_all" ON "bluebell_cbtQuestions" FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS "bluebell_cbtQuestions_update_all" ON "bluebell_cbtQuestions";
CREATE POLICY "bluebell_cbtQuestions_update_all" ON "bluebell_cbtQuestions" FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS "bluebell_cbtQuestions_delete_all" ON "bluebell_cbtQuestions";
CREATE POLICY "bluebell_cbtQuestions_delete_all" ON "bluebell_cbtQuestions" FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_cbt_completion ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_cbt_completion_select_all ON bluebell_cbt_completion;
CREATE POLICY bluebell_cbt_completion_select_all ON bluebell_cbt_completion FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_cbt_completion_insert_all ON bluebell_cbt_completion;
CREATE POLICY bluebell_cbt_completion_insert_all ON bluebell_cbt_completion FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_cbt_completion_update_all ON bluebell_cbt_completion;
CREATE POLICY bluebell_cbt_completion_update_all ON bluebell_cbt_completion FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_cbt_completion_delete_all ON bluebell_cbt_completion;
CREATE POLICY bluebell_cbt_completion_delete_all ON bluebell_cbt_completion FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_cbt_essay ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_cbt_essay_select_all ON bluebell_cbt_essay;
CREATE POLICY bluebell_cbt_essay_select_all ON bluebell_cbt_essay FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_cbt_essay_insert_all ON bluebell_cbt_essay;
CREATE POLICY bluebell_cbt_essay_insert_all ON bluebell_cbt_essay FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_cbt_essay_update_all ON bluebell_cbt_essay;
CREATE POLICY bluebell_cbt_essay_update_all ON bluebell_cbt_essay FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_cbt_essay_delete_all ON bluebell_cbt_essay;
CREATE POLICY bluebell_cbt_essay_delete_all ON bluebell_cbt_essay FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_cbt_results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_cbt_results_select_all ON bluebell_cbt_results;
CREATE POLICY bluebell_cbt_results_select_all ON bluebell_cbt_results FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_cbt_results_insert_all ON bluebell_cbt_results;
CREATE POLICY bluebell_cbt_results_insert_all ON bluebell_cbt_results FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_cbt_results_update_all ON bluebell_cbt_results;
CREATE POLICY bluebell_cbt_results_update_all ON bluebell_cbt_results FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_cbt_results_delete_all ON bluebell_cbt_results;
CREATE POLICY bluebell_cbt_results_delete_all ON bluebell_cbt_results FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_chat_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_chat_conversations_select_all ON bluebell_chat_conversations;
CREATE POLICY bluebell_chat_conversations_select_all ON bluebell_chat_conversations FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_chat_conversations_insert_all ON bluebell_chat_conversations;
CREATE POLICY bluebell_chat_conversations_insert_all ON bluebell_chat_conversations FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_chat_conversations_update_all ON bluebell_chat_conversations;
CREATE POLICY bluebell_chat_conversations_update_all ON bluebell_chat_conversations FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_chat_conversations_delete_all ON bluebell_chat_conversations;
CREATE POLICY bluebell_chat_conversations_delete_all ON bluebell_chat_conversations FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_chat_messages_select_all ON bluebell_chat_messages;
CREATE POLICY bluebell_chat_messages_select_all ON bluebell_chat_messages FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_chat_messages_insert_all ON bluebell_chat_messages;
CREATE POLICY bluebell_chat_messages_insert_all ON bluebell_chat_messages FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_chat_messages_update_all ON bluebell_chat_messages;
CREATE POLICY bluebell_chat_messages_update_all ON bluebell_chat_messages FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_chat_messages_delete_all ON bluebell_chat_messages;
CREATE POLICY bluebell_chat_messages_delete_all ON bluebell_chat_messages FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_class_specific_fees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_class_specific_fees_select_all ON bluebell_class_specific_fees;
CREATE POLICY bluebell_class_specific_fees_select_all ON bluebell_class_specific_fees FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_class_specific_fees_insert_all ON bluebell_class_specific_fees;
CREATE POLICY bluebell_class_specific_fees_insert_all ON bluebell_class_specific_fees FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_class_specific_fees_update_all ON bluebell_class_specific_fees;
CREATE POLICY bluebell_class_specific_fees_update_all ON bluebell_class_specific_fees FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_class_specific_fees_delete_all ON bluebell_class_specific_fees;
CREATE POLICY bluebell_class_specific_fees_delete_all ON bluebell_class_specific_fees FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_classfees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_classfees_select_all ON bluebell_classfees;
CREATE POLICY bluebell_classfees_select_all ON bluebell_classfees FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_classfees_insert_all ON bluebell_classfees;
CREATE POLICY bluebell_classfees_insert_all ON bluebell_classfees FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_classfees_update_all ON bluebell_classfees;
CREATE POLICY bluebell_classfees_update_all ON bluebell_classfees FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_classfees_delete_all ON bluebell_classfees;
CREATE POLICY bluebell_classfees_delete_all ON bluebell_classfees FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_disabled_accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_disabled_accounts_select_all ON bluebell_disabled_accounts;
CREATE POLICY bluebell_disabled_accounts_select_all ON bluebell_disabled_accounts FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_disabled_accounts_insert_all ON bluebell_disabled_accounts;
CREATE POLICY bluebell_disabled_accounts_insert_all ON bluebell_disabled_accounts FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_disabled_accounts_update_all ON bluebell_disabled_accounts;
CREATE POLICY bluebell_disabled_accounts_update_all ON bluebell_disabled_accounts FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_disabled_accounts_delete_all ON bluebell_disabled_accounts;
CREATE POLICY bluebell_disabled_accounts_delete_all ON bluebell_disabled_accounts FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_enquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_enquiries_select_all ON bluebell_enquiries;
CREATE POLICY bluebell_enquiries_select_all ON bluebell_enquiries FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_enquiries_insert_all ON bluebell_enquiries;
CREATE POLICY bluebell_enquiries_insert_all ON bluebell_enquiries FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_enquiries_update_all ON bluebell_enquiries;
CREATE POLICY bluebell_enquiries_update_all ON bluebell_enquiries FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_enquiries_delete_all ON bluebell_enquiries;
CREATE POLICY bluebell_enquiries_delete_all ON bluebell_enquiries FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_lesson_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_lesson_plans_select_all ON bluebell_lesson_plans;
CREATE POLICY bluebell_lesson_plans_select_all ON bluebell_lesson_plans FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_lesson_plans_insert_all ON bluebell_lesson_plans;
CREATE POLICY bluebell_lesson_plans_insert_all ON bluebell_lesson_plans FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_lesson_plans_update_all ON bluebell_lesson_plans;
CREATE POLICY bluebell_lesson_plans_update_all ON bluebell_lesson_plans FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_lesson_plans_delete_all ON bluebell_lesson_plans;
CREATE POLICY bluebell_lesson_plans_delete_all ON bluebell_lesson_plans FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_notes_select_all ON bluebell_notes;
CREATE POLICY bluebell_notes_select_all ON bluebell_notes FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_notes_insert_all ON bluebell_notes;
CREATE POLICY bluebell_notes_insert_all ON bluebell_notes FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_notes_update_all ON bluebell_notes;
CREATE POLICY bluebell_notes_update_all ON bluebell_notes FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_notes_delete_all ON bluebell_notes;
CREATE POLICY bluebell_notes_delete_all ON bluebell_notes FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_paymentsinfo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_paymentsinfo_select_all ON bluebell_paymentsinfo;
CREATE POLICY bluebell_paymentsinfo_select_all ON bluebell_paymentsinfo FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_paymentsinfo_insert_all ON bluebell_paymentsinfo;
CREATE POLICY bluebell_paymentsinfo_insert_all ON bluebell_paymentsinfo FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_paymentsinfo_update_all ON bluebell_paymentsinfo;
CREATE POLICY bluebell_paymentsinfo_update_all ON bluebell_paymentsinfo FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_paymentsinfo_delete_all ON bluebell_paymentsinfo;
CREATE POLICY bluebell_paymentsinfo_delete_all ON bluebell_paymentsinfo FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_result ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_result_select_all ON bluebell_result;
CREATE POLICY bluebell_result_select_all ON bluebell_result FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_result_insert_all ON bluebell_result;
CREATE POLICY bluebell_result_insert_all ON bluebell_result FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_result_update_all ON bluebell_result;
CREATE POLICY bluebell_result_update_all ON bluebell_result FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_result_delete_all ON bluebell_result;
CREATE POLICY bluebell_result_delete_all ON bluebell_result FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_result_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_result_history_select_all ON bluebell_result_history;
CREATE POLICY bluebell_result_history_select_all ON bluebell_result_history FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_result_history_insert_all ON bluebell_result_history;
CREATE POLICY bluebell_result_history_insert_all ON bluebell_result_history FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_result_history_update_all ON bluebell_result_history;
CREATE POLICY bluebell_result_history_update_all ON bluebell_result_history FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_result_history_delete_all ON bluebell_result_history;
CREATE POLICY bluebell_result_history_delete_all ON bluebell_result_history FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_secretaryauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_secretaryauth_select_all ON bluebell_secretaryauth;
CREATE POLICY bluebell_secretaryauth_select_all ON bluebell_secretaryauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_secretaryauth_insert_all ON bluebell_secretaryauth;
CREATE POLICY bluebell_secretaryauth_insert_all ON bluebell_secretaryauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_secretaryauth_update_all ON bluebell_secretaryauth;
CREATE POLICY bluebell_secretaryauth_update_all ON bluebell_secretaryauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_secretaryauth_delete_all ON bluebell_secretaryauth;
CREATE POLICY bluebell_secretaryauth_delete_all ON bluebell_secretaryauth FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_settings_select_all ON bluebell_settings;
CREATE POLICY bluebell_settings_select_all ON bluebell_settings FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_settings_insert_all ON bluebell_settings;
CREATE POLICY bluebell_settings_insert_all ON bluebell_settings FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_settings_update_all ON bluebell_settings;
CREATE POLICY bluebell_settings_update_all ON bluebell_settings FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_settings_delete_all ON bluebell_settings;
CREATE POLICY bluebell_settings_delete_all ON bluebell_settings FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_staff ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_staff_select_all ON bluebell_staff;
CREATE POLICY bluebell_staff_select_all ON bluebell_staff FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_staff_insert_all ON bluebell_staff;
CREATE POLICY bluebell_staff_insert_all ON bluebell_staff FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_update_all ON bluebell_staff;
CREATE POLICY bluebell_staff_update_all ON bluebell_staff FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_delete_all ON bluebell_staff;
CREATE POLICY bluebell_staff_delete_all ON bluebell_staff FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_staff_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_staff_assignments_select_all ON bluebell_staff_assignments;
CREATE POLICY bluebell_staff_assignments_select_all ON bluebell_staff_assignments FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_staff_assignments_insert_all ON bluebell_staff_assignments;
CREATE POLICY bluebell_staff_assignments_insert_all ON bluebell_staff_assignments FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_assignments_update_all ON bluebell_staff_assignments;
CREATE POLICY bluebell_staff_assignments_update_all ON bluebell_staff_assignments FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_assignments_delete_all ON bluebell_staff_assignments;
CREATE POLICY bluebell_staff_assignments_delete_all ON bluebell_staff_assignments FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_staff_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_staff_attendance_select_all ON bluebell_staff_attendance;
CREATE POLICY bluebell_staff_attendance_select_all ON bluebell_staff_attendance FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_staff_attendance_insert_all ON bluebell_staff_attendance;
CREATE POLICY bluebell_staff_attendance_insert_all ON bluebell_staff_attendance FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_attendance_update_all ON bluebell_staff_attendance;
CREATE POLICY bluebell_staff_attendance_update_all ON bluebell_staff_attendance FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_attendance_delete_all ON bluebell_staff_attendance;
CREATE POLICY bluebell_staff_attendance_delete_all ON bluebell_staff_attendance FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_staff_credentials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_staff_credentials_select_all ON bluebell_staff_credentials;
CREATE POLICY bluebell_staff_credentials_select_all ON bluebell_staff_credentials FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_staff_credentials_insert_all ON bluebell_staff_credentials;
CREATE POLICY bluebell_staff_credentials_insert_all ON bluebell_staff_credentials FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_credentials_update_all ON bluebell_staff_credentials;
CREATE POLICY bluebell_staff_credentials_update_all ON bluebell_staff_credentials FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_staff_credentials_delete_all ON bluebell_staff_credentials;
CREATE POLICY bluebell_staff_credentials_delete_all ON bluebell_staff_credentials FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_student ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_student_select_all ON bluebell_student;
CREATE POLICY bluebell_student_select_all ON bluebell_student FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_student_insert_all ON bluebell_student;
CREATE POLICY bluebell_student_insert_all ON bluebell_student FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_student_update_all ON bluebell_student;
CREATE POLICY bluebell_student_update_all ON bluebell_student FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_student_delete_all ON bluebell_student;
CREATE POLICY bluebell_student_delete_all ON bluebell_student FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_teacherauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_teacherauth_select_all ON bluebell_teacherauth;
CREATE POLICY bluebell_teacherauth_select_all ON bluebell_teacherauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_teacherauth_insert_all ON bluebell_teacherauth;
CREATE POLICY bluebell_teacherauth_insert_all ON bluebell_teacherauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_teacherauth_update_all ON bluebell_teacherauth;
CREATE POLICY bluebell_teacherauth_update_all ON bluebell_teacherauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_teacherauth_delete_all ON bluebell_teacherauth;
CREATE POLICY bluebell_teacherauth_delete_all ON bluebell_teacherauth FOR DELETE TO anon, authenticated using (true);

ALTER TABLE bluebell_userauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bluebell_userauth_select_all ON bluebell_userauth;
CREATE POLICY bluebell_userauth_select_all ON bluebell_userauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS bluebell_userauth_insert_all ON bluebell_userauth;
CREATE POLICY bluebell_userauth_insert_all ON bluebell_userauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_userauth_update_all ON bluebell_userauth;
CREATE POLICY bluebell_userauth_update_all ON bluebell_userauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS bluebell_userauth_delete_all ON bluebell_userauth;
CREATE POLICY bluebell_userauth_delete_all ON bluebell_userauth FOR DELETE TO anon, authenticated using (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
