-- 02_rls.sql — Bluebell's data-access posture.
-- Generated by tools/gen-schema.mjs — do not hand-edit; re-run the tool.
-- The five portals talk to PostgREST with the public anon key (the browser
-- holds no service-role credential), so every provisioned table needs
-- permissive policies for anon + authenticated. This mirrors the posture the
-- repo's own setup scripts use (jmis_cbt_results_setup.sql,
-- platform_academics_rls_fix.sql). Re-runnable: each policy is dropped first.
--
-- NOTE: this is an open posture by design for a school-internal system where
-- the apps are the only clients. Tighten it per table once Bluebell's real
-- role model is in place — see README.md "Locking the database down".

set search_path = public;

ALTER TABLE devauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS devauth_select_all ON devauth;
CREATE POLICY devauth_select_all ON devauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS devauth_insert_all ON devauth;
CREATE POLICY devauth_insert_all ON devauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS devauth_update_all ON devauth;
CREATE POLICY devauth_update_all ON devauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS devauth_delete_all ON devauth;
CREATE POLICY devauth_delete_all ON devauth FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_admissions_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_admissions_applications_select_all ON jmis_admissions_applications;
CREATE POLICY jmis_admissions_applications_select_all ON jmis_admissions_applications FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_admissions_applications_insert_all ON jmis_admissions_applications;
CREATE POLICY jmis_admissions_applications_insert_all ON jmis_admissions_applications FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_admissions_applications_update_all ON jmis_admissions_applications;
CREATE POLICY jmis_admissions_applications_update_all ON jmis_admissions_applications FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_admissions_applications_delete_all ON jmis_admissions_applications;
CREATE POLICY jmis_admissions_applications_delete_all ON jmis_admissions_applications FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_announcements_select_all ON jmis_announcements;
CREATE POLICY jmis_announcements_select_all ON jmis_announcements FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_announcements_insert_all ON jmis_announcements;
CREATE POLICY jmis_announcements_insert_all ON jmis_announcements FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_announcements_update_all ON jmis_announcements;
CREATE POLICY jmis_announcements_update_all ON jmis_announcements FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_announcements_delete_all ON jmis_announcements;
CREATE POLICY jmis_announcements_delete_all ON jmis_announcements FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_assignment_submissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_assignment_submissions_select_all ON jmis_assignment_submissions;
CREATE POLICY jmis_assignment_submissions_select_all ON jmis_assignment_submissions FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_assignment_submissions_insert_all ON jmis_assignment_submissions;
CREATE POLICY jmis_assignment_submissions_insert_all ON jmis_assignment_submissions FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_assignment_submissions_update_all ON jmis_assignment_submissions;
CREATE POLICY jmis_assignment_submissions_update_all ON jmis_assignment_submissions FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_assignment_submissions_delete_all ON jmis_assignment_submissions;
CREATE POLICY jmis_assignment_submissions_delete_all ON jmis_assignment_submissions FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_assignments_select_all ON jmis_assignments;
CREATE POLICY jmis_assignments_select_all ON jmis_assignments FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_assignments_insert_all ON jmis_assignments;
CREATE POLICY jmis_assignments_insert_all ON jmis_assignments FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_assignments_update_all ON jmis_assignments;
CREATE POLICY jmis_assignments_update_all ON jmis_assignments FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_assignments_delete_all ON jmis_assignments;
CREATE POLICY jmis_assignments_delete_all ON jmis_assignments FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_attendance_select_all ON jmis_attendance;
CREATE POLICY jmis_attendance_select_all ON jmis_attendance FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_attendance_insert_all ON jmis_attendance;
CREATE POLICY jmis_attendance_insert_all ON jmis_attendance FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_attendance_update_all ON jmis_attendance;
CREATE POLICY jmis_attendance_update_all ON jmis_attendance FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_attendance_delete_all ON jmis_attendance;
CREATE POLICY jmis_attendance_delete_all ON jmis_attendance FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_auditlogs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_auditlogs_select_all ON jmis_auditlogs;
CREATE POLICY jmis_auditlogs_select_all ON jmis_auditlogs FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_auditlogs_insert_all ON jmis_auditlogs;
CREATE POLICY jmis_auditlogs_insert_all ON jmis_auditlogs FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_auditlogs_update_all ON jmis_auditlogs;
CREATE POLICY jmis_auditlogs_update_all ON jmis_auditlogs FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_auditlogs_delete_all ON jmis_auditlogs;
CREATE POLICY jmis_auditlogs_delete_all ON jmis_auditlogs FOR DELETE TO anon, authenticated using (true);

ALTER TABLE "jmis_cbtQuestions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "jmis_cbtQuestions_select_all" ON "jmis_cbtQuestions";
CREATE POLICY "jmis_cbtQuestions_select_all" ON "jmis_cbtQuestions" FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS "jmis_cbtQuestions_insert_all" ON "jmis_cbtQuestions";
CREATE POLICY "jmis_cbtQuestions_insert_all" ON "jmis_cbtQuestions" FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS "jmis_cbtQuestions_update_all" ON "jmis_cbtQuestions";
CREATE POLICY "jmis_cbtQuestions_update_all" ON "jmis_cbtQuestions" FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS "jmis_cbtQuestions_delete_all" ON "jmis_cbtQuestions";
CREATE POLICY "jmis_cbtQuestions_delete_all" ON "jmis_cbtQuestions" FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_cbt_completion ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_cbt_completion_select_all ON jmis_cbt_completion;
CREATE POLICY jmis_cbt_completion_select_all ON jmis_cbt_completion FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_cbt_completion_insert_all ON jmis_cbt_completion;
CREATE POLICY jmis_cbt_completion_insert_all ON jmis_cbt_completion FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_cbt_completion_update_all ON jmis_cbt_completion;
CREATE POLICY jmis_cbt_completion_update_all ON jmis_cbt_completion FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_cbt_completion_delete_all ON jmis_cbt_completion;
CREATE POLICY jmis_cbt_completion_delete_all ON jmis_cbt_completion FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_cbt_essay ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_cbt_essay_select_all ON jmis_cbt_essay;
CREATE POLICY jmis_cbt_essay_select_all ON jmis_cbt_essay FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_cbt_essay_insert_all ON jmis_cbt_essay;
CREATE POLICY jmis_cbt_essay_insert_all ON jmis_cbt_essay FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_cbt_essay_update_all ON jmis_cbt_essay;
CREATE POLICY jmis_cbt_essay_update_all ON jmis_cbt_essay FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_cbt_essay_delete_all ON jmis_cbt_essay;
CREATE POLICY jmis_cbt_essay_delete_all ON jmis_cbt_essay FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_cbt_results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_cbt_results_select_all ON jmis_cbt_results;
CREATE POLICY jmis_cbt_results_select_all ON jmis_cbt_results FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_cbt_results_insert_all ON jmis_cbt_results;
CREATE POLICY jmis_cbt_results_insert_all ON jmis_cbt_results FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_cbt_results_update_all ON jmis_cbt_results;
CREATE POLICY jmis_cbt_results_update_all ON jmis_cbt_results FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_cbt_results_delete_all ON jmis_cbt_results;
CREATE POLICY jmis_cbt_results_delete_all ON jmis_cbt_results FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_chat_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_chat_conversations_select_all ON jmis_chat_conversations;
CREATE POLICY jmis_chat_conversations_select_all ON jmis_chat_conversations FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_chat_conversations_insert_all ON jmis_chat_conversations;
CREATE POLICY jmis_chat_conversations_insert_all ON jmis_chat_conversations FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_chat_conversations_update_all ON jmis_chat_conversations;
CREATE POLICY jmis_chat_conversations_update_all ON jmis_chat_conversations FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_chat_conversations_delete_all ON jmis_chat_conversations;
CREATE POLICY jmis_chat_conversations_delete_all ON jmis_chat_conversations FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_chat_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_chat_messages_select_all ON jmis_chat_messages;
CREATE POLICY jmis_chat_messages_select_all ON jmis_chat_messages FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_chat_messages_insert_all ON jmis_chat_messages;
CREATE POLICY jmis_chat_messages_insert_all ON jmis_chat_messages FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_chat_messages_update_all ON jmis_chat_messages;
CREATE POLICY jmis_chat_messages_update_all ON jmis_chat_messages FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_chat_messages_delete_all ON jmis_chat_messages;
CREATE POLICY jmis_chat_messages_delete_all ON jmis_chat_messages FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_class_specific_fees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_class_specific_fees_select_all ON jmis_class_specific_fees;
CREATE POLICY jmis_class_specific_fees_select_all ON jmis_class_specific_fees FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_class_specific_fees_insert_all ON jmis_class_specific_fees;
CREATE POLICY jmis_class_specific_fees_insert_all ON jmis_class_specific_fees FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_class_specific_fees_update_all ON jmis_class_specific_fees;
CREATE POLICY jmis_class_specific_fees_update_all ON jmis_class_specific_fees FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_class_specific_fees_delete_all ON jmis_class_specific_fees;
CREATE POLICY jmis_class_specific_fees_delete_all ON jmis_class_specific_fees FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_classfees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_classfees_select_all ON jmis_classfees;
CREATE POLICY jmis_classfees_select_all ON jmis_classfees FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_classfees_insert_all ON jmis_classfees;
CREATE POLICY jmis_classfees_insert_all ON jmis_classfees FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_classfees_update_all ON jmis_classfees;
CREATE POLICY jmis_classfees_update_all ON jmis_classfees FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_classfees_delete_all ON jmis_classfees;
CREATE POLICY jmis_classfees_delete_all ON jmis_classfees FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_disabled_accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_disabled_accounts_select_all ON jmis_disabled_accounts;
CREATE POLICY jmis_disabled_accounts_select_all ON jmis_disabled_accounts FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_disabled_accounts_insert_all ON jmis_disabled_accounts;
CREATE POLICY jmis_disabled_accounts_insert_all ON jmis_disabled_accounts FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_disabled_accounts_update_all ON jmis_disabled_accounts;
CREATE POLICY jmis_disabled_accounts_update_all ON jmis_disabled_accounts FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_disabled_accounts_delete_all ON jmis_disabled_accounts;
CREATE POLICY jmis_disabled_accounts_delete_all ON jmis_disabled_accounts FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_enquiries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_enquiries_select_all ON jmis_enquiries;
CREATE POLICY jmis_enquiries_select_all ON jmis_enquiries FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_enquiries_insert_all ON jmis_enquiries;
CREATE POLICY jmis_enquiries_insert_all ON jmis_enquiries FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_enquiries_update_all ON jmis_enquiries;
CREATE POLICY jmis_enquiries_update_all ON jmis_enquiries FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_enquiries_delete_all ON jmis_enquiries;
CREATE POLICY jmis_enquiries_delete_all ON jmis_enquiries FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_lesson_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_lesson_plans_select_all ON jmis_lesson_plans;
CREATE POLICY jmis_lesson_plans_select_all ON jmis_lesson_plans FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_lesson_plans_insert_all ON jmis_lesson_plans;
CREATE POLICY jmis_lesson_plans_insert_all ON jmis_lesson_plans FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_lesson_plans_update_all ON jmis_lesson_plans;
CREATE POLICY jmis_lesson_plans_update_all ON jmis_lesson_plans FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_lesson_plans_delete_all ON jmis_lesson_plans;
CREATE POLICY jmis_lesson_plans_delete_all ON jmis_lesson_plans FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_notes_select_all ON jmis_notes;
CREATE POLICY jmis_notes_select_all ON jmis_notes FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_notes_insert_all ON jmis_notes;
CREATE POLICY jmis_notes_insert_all ON jmis_notes FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_notes_update_all ON jmis_notes;
CREATE POLICY jmis_notes_update_all ON jmis_notes FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_notes_delete_all ON jmis_notes;
CREATE POLICY jmis_notes_delete_all ON jmis_notes FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_paymentsinfo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_paymentsinfo_select_all ON jmis_paymentsinfo;
CREATE POLICY jmis_paymentsinfo_select_all ON jmis_paymentsinfo FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_paymentsinfo_insert_all ON jmis_paymentsinfo;
CREATE POLICY jmis_paymentsinfo_insert_all ON jmis_paymentsinfo FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_paymentsinfo_update_all ON jmis_paymentsinfo;
CREATE POLICY jmis_paymentsinfo_update_all ON jmis_paymentsinfo FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_paymentsinfo_delete_all ON jmis_paymentsinfo;
CREATE POLICY jmis_paymentsinfo_delete_all ON jmis_paymentsinfo FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_result ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_result_select_all ON jmis_result;
CREATE POLICY jmis_result_select_all ON jmis_result FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_result_insert_all ON jmis_result;
CREATE POLICY jmis_result_insert_all ON jmis_result FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_result_update_all ON jmis_result;
CREATE POLICY jmis_result_update_all ON jmis_result FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_result_delete_all ON jmis_result;
CREATE POLICY jmis_result_delete_all ON jmis_result FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_result_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_result_history_select_all ON jmis_result_history;
CREATE POLICY jmis_result_history_select_all ON jmis_result_history FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_result_history_insert_all ON jmis_result_history;
CREATE POLICY jmis_result_history_insert_all ON jmis_result_history FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_result_history_update_all ON jmis_result_history;
CREATE POLICY jmis_result_history_update_all ON jmis_result_history FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_result_history_delete_all ON jmis_result_history;
CREATE POLICY jmis_result_history_delete_all ON jmis_result_history FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_secretaryauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_secretaryauth_select_all ON jmis_secretaryauth;
CREATE POLICY jmis_secretaryauth_select_all ON jmis_secretaryauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_secretaryauth_insert_all ON jmis_secretaryauth;
CREATE POLICY jmis_secretaryauth_insert_all ON jmis_secretaryauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_secretaryauth_update_all ON jmis_secretaryauth;
CREATE POLICY jmis_secretaryauth_update_all ON jmis_secretaryauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_secretaryauth_delete_all ON jmis_secretaryauth;
CREATE POLICY jmis_secretaryauth_delete_all ON jmis_secretaryauth FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_settings_select_all ON jmis_settings;
CREATE POLICY jmis_settings_select_all ON jmis_settings FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_settings_insert_all ON jmis_settings;
CREATE POLICY jmis_settings_insert_all ON jmis_settings FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_settings_update_all ON jmis_settings;
CREATE POLICY jmis_settings_update_all ON jmis_settings FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_settings_delete_all ON jmis_settings;
CREATE POLICY jmis_settings_delete_all ON jmis_settings FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_staff ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_staff_select_all ON jmis_staff;
CREATE POLICY jmis_staff_select_all ON jmis_staff FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_staff_insert_all ON jmis_staff;
CREATE POLICY jmis_staff_insert_all ON jmis_staff FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_update_all ON jmis_staff;
CREATE POLICY jmis_staff_update_all ON jmis_staff FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_delete_all ON jmis_staff;
CREATE POLICY jmis_staff_delete_all ON jmis_staff FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_staff_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_staff_assignments_select_all ON jmis_staff_assignments;
CREATE POLICY jmis_staff_assignments_select_all ON jmis_staff_assignments FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_staff_assignments_insert_all ON jmis_staff_assignments;
CREATE POLICY jmis_staff_assignments_insert_all ON jmis_staff_assignments FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_assignments_update_all ON jmis_staff_assignments;
CREATE POLICY jmis_staff_assignments_update_all ON jmis_staff_assignments FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_assignments_delete_all ON jmis_staff_assignments;
CREATE POLICY jmis_staff_assignments_delete_all ON jmis_staff_assignments FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_staff_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_staff_attendance_select_all ON jmis_staff_attendance;
CREATE POLICY jmis_staff_attendance_select_all ON jmis_staff_attendance FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_staff_attendance_insert_all ON jmis_staff_attendance;
CREATE POLICY jmis_staff_attendance_insert_all ON jmis_staff_attendance FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_attendance_update_all ON jmis_staff_attendance;
CREATE POLICY jmis_staff_attendance_update_all ON jmis_staff_attendance FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_attendance_delete_all ON jmis_staff_attendance;
CREATE POLICY jmis_staff_attendance_delete_all ON jmis_staff_attendance FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_staff_credentials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_staff_credentials_select_all ON jmis_staff_credentials;
CREATE POLICY jmis_staff_credentials_select_all ON jmis_staff_credentials FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_staff_credentials_insert_all ON jmis_staff_credentials;
CREATE POLICY jmis_staff_credentials_insert_all ON jmis_staff_credentials FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_credentials_update_all ON jmis_staff_credentials;
CREATE POLICY jmis_staff_credentials_update_all ON jmis_staff_credentials FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_staff_credentials_delete_all ON jmis_staff_credentials;
CREATE POLICY jmis_staff_credentials_delete_all ON jmis_staff_credentials FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_student ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_student_select_all ON jmis_student;
CREATE POLICY jmis_student_select_all ON jmis_student FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_student_insert_all ON jmis_student;
CREATE POLICY jmis_student_insert_all ON jmis_student FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_student_update_all ON jmis_student;
CREATE POLICY jmis_student_update_all ON jmis_student FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_student_delete_all ON jmis_student;
CREATE POLICY jmis_student_delete_all ON jmis_student FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_teacherauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_teacherauth_select_all ON jmis_teacherauth;
CREATE POLICY jmis_teacherauth_select_all ON jmis_teacherauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_teacherauth_insert_all ON jmis_teacherauth;
CREATE POLICY jmis_teacherauth_insert_all ON jmis_teacherauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_teacherauth_update_all ON jmis_teacherauth;
CREATE POLICY jmis_teacherauth_update_all ON jmis_teacherauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_teacherauth_delete_all ON jmis_teacherauth;
CREATE POLICY jmis_teacherauth_delete_all ON jmis_teacherauth FOR DELETE TO anon, authenticated using (true);

ALTER TABLE jmis_userauth ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jmis_userauth_select_all ON jmis_userauth;
CREATE POLICY jmis_userauth_select_all ON jmis_userauth FOR SELECT TO anon, authenticated using (true);
DROP POLICY IF EXISTS jmis_userauth_insert_all ON jmis_userauth;
CREATE POLICY jmis_userauth_insert_all ON jmis_userauth FOR INSERT TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_userauth_update_all ON jmis_userauth;
CREATE POLICY jmis_userauth_update_all ON jmis_userauth FOR UPDATE TO anon, authenticated with check (true);
DROP POLICY IF EXISTS jmis_userauth_delete_all ON jmis_userauth;
CREATE POLICY jmis_userauth_delete_all ON jmis_userauth FOR DELETE TO anon, authenticated using (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
