-- 03_storage.sql — the public buckets the clone uploads into.
-- Generated by tools/gen-schema.mjs — do not hand-edit; re-run the tool.
--   setting         hero/gallery/facility/testimonial + passport art
--   passport        pupil photos        staff_passport  staff photos
--   cbt             exam attachments and academics uploads

insert into storage.buckets (id, name, public) values ('cbt', 'cbt', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('images', 'images', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('passport', 'passport', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('setting', 'setting', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('staff_passport', 'staff_passport', true) on conflict (id) do nothing;

drop policy if exists jmis_cbt_select on storage.objects;
create policy jmis_cbt_select on storage.objects for SELECT to anon, authenticated using (bucket_id = 'cbt');
drop policy if exists jmis_cbt_insert on storage.objects;
create policy jmis_cbt_insert on storage.objects for INSERT to anon, authenticated with check (bucket_id = 'cbt');
drop policy if exists jmis_cbt_update on storage.objects;
create policy jmis_cbt_update on storage.objects for UPDATE to anon, authenticated with check (bucket_id = 'cbt');
drop policy if exists jmis_cbt_delete on storage.objects;
create policy jmis_cbt_delete on storage.objects for DELETE to anon, authenticated using (bucket_id = 'cbt');

drop policy if exists jmis_images_select on storage.objects;
create policy jmis_images_select on storage.objects for SELECT to anon, authenticated using (bucket_id = 'images');
drop policy if exists jmis_images_insert on storage.objects;
create policy jmis_images_insert on storage.objects for INSERT to anon, authenticated with check (bucket_id = 'images');
drop policy if exists jmis_images_update on storage.objects;
create policy jmis_images_update on storage.objects for UPDATE to anon, authenticated with check (bucket_id = 'images');
drop policy if exists jmis_images_delete on storage.objects;
create policy jmis_images_delete on storage.objects for DELETE to anon, authenticated using (bucket_id = 'images');

drop policy if exists jmis_passport_select on storage.objects;
create policy jmis_passport_select on storage.objects for SELECT to anon, authenticated using (bucket_id = 'passport');
drop policy if exists jmis_passport_insert on storage.objects;
create policy jmis_passport_insert on storage.objects for INSERT to anon, authenticated with check (bucket_id = 'passport');
drop policy if exists jmis_passport_update on storage.objects;
create policy jmis_passport_update on storage.objects for UPDATE to anon, authenticated with check (bucket_id = 'passport');
drop policy if exists jmis_passport_delete on storage.objects;
create policy jmis_passport_delete on storage.objects for DELETE to anon, authenticated using (bucket_id = 'passport');

drop policy if exists jmis_setting_select on storage.objects;
create policy jmis_setting_select on storage.objects for SELECT to anon, authenticated using (bucket_id = 'setting');
drop policy if exists jmis_setting_insert on storage.objects;
create policy jmis_setting_insert on storage.objects for INSERT to anon, authenticated with check (bucket_id = 'setting');
drop policy if exists jmis_setting_update on storage.objects;
create policy jmis_setting_update on storage.objects for UPDATE to anon, authenticated with check (bucket_id = 'setting');
drop policy if exists jmis_setting_delete on storage.objects;
create policy jmis_setting_delete on storage.objects for DELETE to anon, authenticated using (bucket_id = 'setting');

drop policy if exists jmis_staff_passport_select on storage.objects;
create policy jmis_staff_passport_select on storage.objects for SELECT to anon, authenticated using (bucket_id = 'staff_passport');
drop policy if exists jmis_staff_passport_insert on storage.objects;
create policy jmis_staff_passport_insert on storage.objects for INSERT to anon, authenticated with check (bucket_id = 'staff_passport');
drop policy if exists jmis_staff_passport_update on storage.objects;
create policy jmis_staff_passport_update on storage.objects for UPDATE to anon, authenticated with check (bucket_id = 'staff_passport');
drop policy if exists jmis_staff_passport_delete on storage.objects;
create policy jmis_staff_passport_delete on storage.objects for DELETE to anon, authenticated using (bucket_id = 'staff_passport');

