// Generates Bluebell's provisioning bundle from JMIS's live PostgREST catalog.
//
//   node tools/gen-schema.mjs [--dry]
//
// Read-only against JMIS; writes only into bluebell/db/. The ONLY contact with
// the JMIS project is a single `GET /rest/v1/` schema read; nothing in the
// emitted SQL is destructive and nothing is ever sent to JMIS.
//
// How the fidelity is achieved:
//   * column names AND Postgres types come from the live JMIS catalog (the
//     OpenAPI document PostgREST publishes), not from a reading of the code;
//   * NOT NULL comes from each definition's `required` list;
//   * primary keys and foreign keys come from the `<pk/>` / `<fk table=… />`
//     markers PostgREST writes into each column's description;
//   * the table *set* is derived from what the clone's own code calls, so
//     Bluebell provisions exactly the surface the five apps use;
//   * Bluebell keeps JMIS's `jmis_*` table names verbatim (brand.json
//     renameTables=false): the clone gets its OWN Supabase project, so there is
//     no shared-database reason to rename, and byte-parallel identifiers keep
//     future JMIS fixes portable. renameTable() below is the single switch.
//   * indexes and RLS policies are not in the catalog, so they are replayed
//     from the repo's authored `src/api/*.sql` (00_indexes.sql) and written to
//     match the project's existing permissive posture (02_rls.sql).
//
// Outputs, in the order they must be pasted:
//   db/01_schema.sql        CREATE TABLE (+ deferred FKs)
//   db/02_rls.sql           RLS enable + permissive policies for anon/authenticated
//   db/00_indexes.sql       indexes + policies authored in src/api, pasted third
//                           because its statements need the tables to exist
//   db/03_storage.sql       public buckets + storage policies
//   db/04_seed_bluebell.sql the single jmis_settings row + first admin grant
//   db/apply_all.sql        the five concatenated in paste order
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { ROOT, BRAND, backend } from './guard.mjs';

const DB = join(ROOT, 'db');
const JMIS_ENV = join(BRAND.source.root, 'jmischool', '.env');
const DRY = process.argv.includes('--dry');

const PREFIX = BRAND.tablePrefix;               // 'jmis' for Bluebell
const ADMIN = BRAND.dirs[0];                     // bluebellschool (holds src/api/*.sql)
const APPS = BRAND.dirs;
const SETTINGS = `${PREFIX}_settings`;
const USERAUTH = `${PREFIX}_userauth`;
const TRY = 'bb_try';                            // guarded-execution helper name
const SKIP = new Set(['node_modules', '.next', '.git', '.expo', '.swc', 'dist', 'build', 'out', 'android', 'ios', 'coverage']);
const CODE_EXT = new Set(['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs']);

// Role/lookup tables that Supabase auth and the login screens read; some are
// referenced only through string-built callsites, so they are listed explicitly.
const ALWAYS = [
  `${PREFIX}_userauth`,
  'devauth',
  `${PREFIX}_teacherauth`,
  `${PREFIX}_secretaryauth`,
  `${PREFIX}_disabled_accounts`,
  SETTINGS,
];
const BUCKETS = ['setting', 'passport', 'staff_passport', 'cbt'];

// ---------------------------------------------------------------- utilities
const STAMP = 'Generated by tools/gen-schema.mjs — do not hand-edit; re-run the tool.';

/**
 * Maps a JMIS catalog name to the name Bluebell provisions. With
 * brand.json.renameTables=false this is the identity, so `jmis_*` is preserved;
 * if a future build shares a database it flips to `<prefix>_*` in one place.
 */
const renameTable = (t) => (BRAND.renameTables ? t.replace(/^jmis_/, `${PREFIX}_`) : t);

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_0-9]+)\s*=\s*(.*)$/);
    if (!m) continue;
    out[m[1]] = m[2].trim().replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
  }
  return out;
}

function walk(dir, acc = []) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const e of entries) {
    if (e.isDirectory()) {
      if (!SKIP.has(e.name)) walk(join(dir, e.name), acc);
    } else if (CODE_EXT.has(e.name.slice(e.name.lastIndexOf('.')))) {
      acc.push(join(dir, e.name));
    }
  }
  return acc;
}

/** Postgres folds unquoted identifiers to lowercase; quote anything else. */
const q = (name) => (/^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name}"`);

/** Maps a PostgREST/OpenAPI column descriptor to a Postgres type. */
function sqlType(col) {
  const f = col.format || '';
  switch (f) {
    case 'character varying':
    case 'character':
    case 'text':
    case 'citext':
    case 'name':
      return 'text';
    case 'uuid':
      return 'uuid';
    case 'integer':
    case 'int':
    case 'int4':
      return 'integer';
    case 'bigint':
    case 'int8':
      return 'bigint';
    case 'smallint':
    case 'int2':
      return 'smallint';
    case 'numeric':
    case 'decimal':
      return 'numeric';
    case 'real':
    case 'float4':
      return 'real';
    case 'double precision':
    case 'float8':
      return 'double precision';
    case 'boolean':
    case 'bool':
      return 'boolean';
    case 'date':
      return 'date';
    case 'timestamp with time zone':
      return 'timestamp with time zone';
    case 'timestamp without time zone':
      return 'timestamp without time zone';
    case 'time with time zone':
    case 'time without time zone':
      return 'time';
    case 'interval':
      return 'interval';
    case 'jsonb':
      return 'jsonb';
    case 'json':
      return 'json';
    case 'bytea':
      return 'bytea';
    default:
      if (f.endsWith('[]')) return f; // arrays are already spelled `<elem>[]`
      return 'text';
  }
}

const isPk = (col) => /Primary Key/.test(col.description || '');
const fkTarget = (col) => {
  const m = (col.description || '').match(/<fk table='([^']+)' column='([^']+)'/);
  return m ? { table: renameTable(m[1]), column: m[2] } : null;
};

/** Splits a SQL file into statements, honouring quotes, comments and $$ bodies. */
function splitSql(text) {
  const out = [];
  let cur = '';
  let i = 0;
  while (i < text.length) {
    const ch = text[i];
    const two = text.slice(i, i + 2);
    if (two === '--') {
      const nl = text.indexOf('\n', i);
      const end = nl === -1 ? text.length : nl + 1;
      cur += text.slice(i, end);
      i = end;
      continue;
    }
    if (two === '/*') {
      const end = text.indexOf('*/', i + 2);
      const stop = end === -1 ? text.length : end + 2;
      cur += text.slice(i, stop);
      i = stop;
      continue;
    }
    if (ch === "'" || ch === '"') {
      const start = i;
      i += 1;
      while (i < text.length) {
        if (text[i] === '\\') { i += 2; continue; }
        if (text[i] === ch) { if (text[i + 1] === ch) { i += 2; continue; } i += 1; break; }
        i += 1;
      }
      cur += text.slice(start, i);
      continue;
    }
    const tagMatch = /^\$\$\w*\$\$/.exec(text.slice(i, i + 32));
    if (tagMatch) {
      const tag = tagMatch[1] ?? tagMatch[0];
      const end = text.indexOf(tag, i + tag.length);
      const stop = end === -1 ? text.length : end + tag.length;
      cur += text.slice(i, stop);
      i = stop;
      continue;
    }
    if (ch === ';') {
      out.push(cur + ';');
      cur = '';
      i += 1;
      continue;
    }
    cur += ch;
    i += 1;
  }
  if (cur.trim()) out.push(cur);
  return out.map((s) => s.trim()).filter(Boolean);
}

const json = (v) => JSON.stringify(v).replace(/'/g, "''");

// ------------------------------------------------------------------ inputs
const jmisEnv = parseEnv(readFileSync(JMIS_ENV, 'utf8'));
const jmisUrl = jmisEnv.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = jmisEnv.SUPABASE_SERVICE_ROLE_KEY;
if (!jmisUrl || !serviceKey) throw new Error('JMIS Supabase URL / service-role key missing in ' + JMIS_ENV);

// Bluebell's own project ref, for the README. Until the keys are supplied this
// is the placeholder; the catalog read below is always against JMIS (read-only).
const BE = backend();
const bluebellProject = BE.ref;

console.log(`reading JMIS catalog (read-only): ${jmisUrl}/rest/v1/`);
const res = await fetch(jmisUrl + '/rest/v1/', {
  headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` },
});
if (!res.ok) throw new Error(`catalog fetch failed: HTTP ${res.status}`);
const catalog = await res.json();
// Bluebell keeps JMIS's `jmis_*` names, so renameTable() is the identity here;
// catalogOf() still maps a provisioned name back to the source name so the
// read-only export query and the "skipped" report speak the JMIS-side names.
const rawDefs = catalog.definitions || {};
const defs = {};
const catalogOf = new Map();
for (const [name, def] of Object.entries(rawDefs)) {
  defs[renameTable(name)] = def;
  catalogOf.set(renameTable(name), name);
}
const catalogNames = Object.keys(defs);
console.log(`JMIS catalog: ${catalogNames.length} tables exposed to PostgREST`);

// Which tables does the clone actually call?
const called = new Map(); // table -> Set("app/relative/file")
const calledBuckets = new Set(BUCKETS);
const FROM_RE = /\.(storage\s*\.\s*)?from\(\s*["'`]([^"'`]+)["'`]\s*\)/g;

for (const app of APPS) {
  for (const file of walk(join(ROOT, app))) {
    const text = readFileSync(file, 'utf8');
    const rel = relative(ROOT, file).split(sep).join('/');
    // `.storage.from('bucket')` names a bucket, not a table — the same regex
    // catches both and branches on whether `storage` preceded `from`.
    for (const m of text.matchAll(FROM_RE)) {
      if (m[1]) {
        calledBuckets.add(m[2]);
        continue;
      }
      if (!called.has(m[2])) called.set(m[2], new Set());
      called.get(m[2]).add(rel);
    }
  }
}
for (const t of ALWAYS) if (!called.has(t)) called.set(t, new Set(['tools/gen-schema.mjs (auth/role table)']));

const referenced = [...called.keys()].sort();
const present = new Set(catalogNames);
const toProvision = referenced.filter((t) => present.has(t));
const phantom = referenced.filter((t) => !present.has(t));
const skipped = Object.keys(rawDefs).filter((t) => !called.has(renameTable(t))).sort();

console.log(`referenced by the clone: ${referenced.length}`);
console.log(`  provisioned (exists in JMIS): ${toProvision.length}`);
console.log(`  referenced but absent in JMIS: ${phantom.length}${phantom.length ? ' -> ' + phantom.join(', ') : ''}`);
console.log(`  in JMIS but unused by the clone (not provisioned): ${skipped.length}`);

// ------------------------------------------------------- db/01_schema.sql
const schema = [];
schema.push(`-- 01_schema.sql — Bluebell International School table structure, the same`);
schema.push(`-- columns and names as JMIS (jmis_* preserved verbatim; brand.json`);
schema.push(`-- renameTables=false). Bluebell runs this in its OWN Supabase project.`);
schema.push(`-- ${STAMP}`);
schema.push(`-- Source: the live PostgREST catalog at ${jmisUrl} (column names, Postgres`);
schema.push(`-- types, NOT NULL, primary and foreign keys). Additive and idempotent:`);
schema.push(`-- CREATE TABLE IF NOT EXISTS only, no DROP, no ALTER of existing columns.`);
schema.push(`-- Paste order: 01 -> 02 -> 00 -> 03 -> 04 (see db/README.md).`);
schema.push(``);
schema.push(`set search_path = public;`);
schema.push(``);

const foreignKeys = [];
const typeNotes = [];
for (const table of toProvision) {
  const def = defs[table];
  const props = def.properties || {};
  const required = new Set(def.required || []);
  const cols = [];
  const pks = [];
  for (const [name, col] of Object.entries(props)) {
    let type = sqlType(col);
    if (isPk(col)) pks.push(name);
    // The plan's identity rule: a plain integer surrogate key becomes a bigint
    // identity, so Bluebell never collides with an id the app expects to be unique.
    if (isPk(col) && (type === 'integer' || type === 'bigint')) {
      type = 'bigint generated always as identity';
    } else if (isPk(col) && type === 'uuid' && !/uuid/.test(col.format || '')) {
      type = 'uuid';
    }
    if (!col.format) typeNotes.push(`${table}.${name} (no PostgREST format; emitted as ${type})`);
    cols.push(`  ${q(name)} ${type}${required.has(name) && !isPk(col) ? ' not null' : ''}`);
    const fk = fkTarget(col);
    if (fk && present.has(fk.table)) {
      foreignKeys.push(
        `ALTER TABLE ${q(table)} DROP CONSTRAINT IF EXISTS ${q(`${table}_${name}_fkey`)};\n` +
        `ALTER TABLE ${q(table)} ADD CONSTRAINT ${q(`${table}_${name}_fkey`)} ` +
        `FOREIGN KEY (${q(name)}) REFERENCES ${q(fk.table)} (${q(fk.column)}) NOT VALID;`
      );
    }
  }
  if (pks.length) cols.push(`  PRIMARY KEY (${pks.map(q).join(', ')})`);
  schema.push(`-- ${table}  (${Object.keys(props).length} columns${pks.length ? `, pk ${pks.join(',')}` : ', no primary key'})`);
  schema.push(`CREATE TABLE IF NOT EXISTS ${q(table)} (\n${cols.join(',\n')}\n);`);
  schema.push(``);
}
if (foreignKeys.length) {
  schema.push(`-- Foreign keys (deferred so table order never matters; NOT VALID keeps`);
  schema.push(`-- this non-destructive for any row already present).`);
  schema.push(foreignKeys.join('\n'));
  schema.push(``);
}
schema.push(`-- Done. ${toProvision.length} table(s).`);

// ----------------------------------------------------------- db/02_rls.sql
const rls = [];
rls.push(`-- 02_rls.sql — Bluebell's data-access posture.`);
rls.push(`-- ${STAMP}`);
rls.push(`-- The five portals talk to PostgREST with the public anon key (the browser`);
rls.push(`-- holds no service-role credential), so every provisioned table needs`);
rls.push(`-- permissive policies for anon + authenticated. This mirrors the posture the`);
rls.push(`-- repo's own setup scripts use (jmis_cbt_results_setup.sql,`);
rls.push(`-- platform_academics_rls_fix.sql). Re-runnable: each policy is dropped first.`);
rls.push(`--`);
rls.push(`-- NOTE: this is an open posture by design for a school-internal system where`);
rls.push(`-- the apps are the only clients. Tighten it per table once Bluebell's real`);
rls.push(`-- role model is in place — see README.md "Locking the database down".`);
rls.push(``);
rls.push(`set search_path = public;`);
rls.push(``);
for (const table of toProvision) {
  const t = q(table);
  rls.push(`ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;`);
  for (const cmd of ['select', 'insert', 'update', 'delete']) {
    const using = cmd === 'select' || cmd === 'delete' ? 'using (true)' : 'with check (true)';
    rls.push(`DROP POLICY IF EXISTS ${q(`${table}_${cmd}_all`)} ON ${t};`);
    rls.push(`CREATE POLICY ${q(`${table}_${cmd}_all`)} ON ${t} FOR ${cmd.toUpperCase()} TO anon, authenticated ${using};`);
  }
  rls.push(``);
}
rls.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;`);
rls.push(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;`);

// ------------------------------------------------------- db/03_storage.sql
const buckets = [...calledBuckets].sort();
const sto = [];
sto.push(`-- 03_storage.sql — the public buckets the clone uploads into.`);
sto.push(`-- ${STAMP}`);
sto.push(`--   setting         hero/gallery/facility/testimonial + passport art`);
sto.push(`--   passport        pupil photos        staff_passport  staff photos`);
sto.push(`--   cbt             exam attachments and academics uploads`);
sto.push(``);
for (const b of buckets) {
  sto.push(`insert into storage.buckets (id, name, public) values ('${b}', '${b}', true) on conflict (id) do nothing;`);
}
sto.push(``);
for (const b of buckets) {
  for (const cmd of ['select', 'insert', 'update', 'delete']) {
    const using = cmd === 'select' || cmd === 'delete' ? 'using' : 'with check';
    sto.push(`drop policy if exists ${q(`${PREFIX}_${b}_${cmd}`)} on storage.objects;`);
    sto.push(`create policy ${q(`${PREFIX}_${b}_${cmd}`)} on storage.objects for ${cmd.toUpperCase()} to anon, authenticated ${using} (bucket_id = '${b}');`);
  }
  sto.push(``);
}

// ---------------------------------------------------- db/04_seed_bluebell.sql
const site = JSON.parse(readFileSync(join(ROOT, 'tools', 'site-content.json'), 'utf8'));
const settingsCols = Object.keys(defs[SETTINGS]?.properties || {});
const settingsRow = {
  schoolname: BRAND.school.name,
  session: site.settings?.session || 'BLUEBELL_SESSION_PLACEHOLDER',
  term: site.settings?.term || 'BLUEBELL_TERM_PLACEHOLDER',
  cbtPassword: site.settings?.cbtPassword || 'BLUEBELL_CBT_PASSWORD_PLACEHOLDER',
  adminEmail: site.settings?.adminEmail || 'BLUEBELL_ADMIN_EMAIL_PLACEHOLDER',
  additionalemails: site.settings?.additionalEmails || '',
  nextTermBegins: site.settings?.nextTermBegins || '',
  nextTermFees: site.settings?.nextTermFees ?? 0,
  schoolOpened: site.settings?.schoolOpened ?? 0,
  checkResult: site.settings?.checkResult || '',
  lockResult: site.settings?.lockResult ?? false,
  resultLock: site.settings?.resultLock ?? false,
  use_class_specific_fees: site.settings?.use_class_specific_fees ?? true,
  heroContent: site.heroContent,
  facilitiesContent: site.facilitiesContent,
  galleryContent: site.galleryContent,
  testimonialContent: site.testimonialContent,
  aboutContent: site.aboutContent,
  contactContent: site.contactContent,
};
const seed = [];
seed.push(`-- 04_seed_bluebell.sql — Bluebell's first settings row, so the public site and`);
seed.push(`-- the admin portals come up populated the moment this bundle is pasted.`);
seed.push(`-- ${STAMP}`);
seed.push(`-- Scalar values come from the "settings" block of tools/site-content.json; a`);
seed.push(`-- missing one is emitted as BLUEBELL_*_PLACEHOLDER. Images point at /site/*.jpg`);
seed.push(`-- which ships inside the app (public/site), so nothing has to be uploaded.`);
seed.push(``);
seed.push(`set search_path = public;`);
seed.push(``);
const cols = Object.keys(settingsRow).filter((c) => settingsCols.includes(c) && c !== 'id');
const dropped = Object.keys(settingsRow).filter((c) => !settingsCols.includes(c));
if (dropped.length) console.log(`seed columns absent from ${SETTINGS} (skipped): ${dropped.join(', ')}`);
seed.push(`insert into ${q(SETTINGS)} (${cols.map(q).join(', ')})`);
seed.push(`select ${cols.map((c) => {
  const v = settingsRow[c];
  return typeof v === 'object' ? `'${json(v)}'::jsonb` : `'${String(v).replace(/'/g, "''")}'`;
}).join(', ')}`);
seed.push(`where not exists (select 1 from ${q(SETTINGS)});`);
seed.push(``);
seed.push(`-- Backfill for projects where an earlier version of this seed already ran:`);
seed.push(`-- fills only columns that are still NULL, so values edited through the admin`);
seed.push(`-- Setting page are never overwritten.`);
seed.push(`update ${q(SETTINGS)} set`);
seed.push(cols.filter((c) => ['adminEmail', 'additionalemails', 'nextTermBegins', 'nextTermFees', 'schoolOpened', 'checkResult', 'lockResult', 'resultLock', 'use_class_specific_fees'].includes(c))
  .map((c) => {
    const v = settingsRow[c];
    const lit = typeof v === 'string' ? `'${String(v).replace(/'/g, "''")}'${c === 'checkResult' ? '::date' : ''}` : String(v);
    return `  ${q(c)} = coalesce(${q(c)}, ${lit})`;
  }).join(',\n') + ';');
seed.push(``);
seed.push(`-- The first administrator. Supabase Auth owns the password; this row is what`);
seed.push(`-- the portals read to grant the admin role (src/utils/authUtils.js). Create the`);
seed.push(`-- Auth accounts with: node tools/create-auth-users.mjs --apply`);
if (/PLACEHOLDER/.test(String(settingsRow.adminEmail))) {
  seed.push(`-- BLUEBELL_ADMIN_EMAIL_PLACEHOLDER is still a placeholder — set settings.adminEmail`);
  seed.push(`-- in tools/site-content.json or update this row afterwards.`);
}
seed.push(``);
const uaCols = Object.keys(defs[USERAUTH]?.properties || {});
if (uaCols.length) {
  const uaInsert = uaCols.includes('email') ? ['email'] : [uaCols.find((c) => /mail|user|email/i.test(c))].filter(Boolean);
  if (uaInsert.length) {
    seed.push(`insert into ${q(USERAUTH)} (${uaInsert.map(q).join(', ')})`);
    seed.push(`select ${uaInsert.map(() => `'${String(settingsRow.adminEmail).replace(/'/g, "''")}'`).join(', ')}`);
    seed.push(`where not exists (select 1 from ${q(USERAUTH)});`);
  }
}
seed.push(``);
seed.push(`-- Done.`);

// ------------------------------------------------------- db/00_indexes.sql
// Indexes and policies are not exposed by the catalog, but the repo already
// authored them. Replay only the additive statements from the curated files.
const INDEX_SOURCES = [
  'jmis_cbt_results_setup.sql',
  'jmis_chat_setup.sql',
  'jmis_chat_rls_fix.sql',
  'platform_attendance_signout_setup.sql',
  'platform_attendance_status.sql',
  'platform_attendance_rls_fix.sql',
  'platform_staff_portal_setup.sql',
  'platform_staff_management_setup.sql',
  'platform_staff_rls_fix.sql',
  'platform_student_portal_setup.sql',
  'platform_academics_rls_fix.sql',
  'platform_result_history_rls_fix.sql',
  'platform_website_enquiries_setup.sql',
  'platform_website_rls_fix.sql',
  'jmis_assignment_submissions_setup.sql',
  'jmis_lesson_plan_builder_setup.sql',
  'jmis_disabled_accounts_setup.sql',
  'jmis_staff_credentials.sql',
  'jmis_cbt_created_by.sql',
  'jmis_cbt_max_score.sql',
  'jmis_student_token_count.sql',
  'cbt_score_mapping.sql',
  'class_fees_setup.sql',
  'email_notification_setup.sql',
  'feature_expansion_setup.sql',
  'staff_assignment_unique_index.sql',
];

const KEEP = /^\s*(create\s+(unique\s+)?index|comment\s+on|alter\s+table\s+[\w".]+\s+enable\s+row\s+level\s+security|create\s+policy|drop\s+policy|alter\s+table\s+[\w".]+\s+add\s+constraint)\b/i;
const SKIP_STMT = /\b(drop\s+table|drop\s+column|truncate|delete\s+from|alter\s+column|drop\s+constraint|drop\s+index)\b/i;

// Every kept statement names the table it acts on; anything pointing at a table
// Bluebell does not provision is dropped, because one 42P01 aborts the whole paste.
const stmtTable = (one) => {
  const m =
    one.match(/alter\s+table\s+(?:if\s+exists\s+)?(?:public\.)?([\w"]+)/i) ||
    one.match(/comment\s+on\s+(?:table|column)\s+(?:public\.)?([\w"]+)/i) ||
    // `on` must not swallow a trailing `ON DELETE` clause from a constraint.
    one.match(/\bon\s+(?:public\.)?([\w"]+)(?!\s+(?:delete|update|cascade|restrict|set\s+null|no\s+action))/i);
  if (!m) return null;
  return m[1].replace(/^"|"$/g, '');
};

const idx = [];
idx.push(`-- 00_indexes.sql — indexes, policies and constraints the clone's own setup`);
idx.push(`-- scripts author for the newer tables. The PostgREST catalog exposes no index`);
idx.push(`-- information, so these are replayed from ${ADMIN}/src/api/*.sql and pruned`);
idx.push(`-- to statements that can only add: CREATE INDEX / POLICY / CONSTRAINT, COMMENT,`);
idx.push(`-- ENABLE ROW LEVEL SECURITY. Anything destructive or column-altering is`);
idx.push(`-- dropped from the bundle (01_schema.sql already carries every live column).`);
idx.push(`-- The surviving statements are executed through ${TRY}(), which reports and`);
idx.push(`-- skips failures, so it can be re-run freely. Every statement here needs`);
idx.push(`-- its table to exist first, so paste it after 01_schema.sql and 02_rls.sql.`);
idx.push(`-- ${STAMP}`);
idx.push(``);
idx.push(`set search_path = public;`);
idx.push(``);
let kept = 0;
let pruned = 0;
let prunedTable = 0;
const stmtList = [];
const seenStmt = new Set();
const provisioned = new Set(toProvision);
for (const file of INDEX_SOURCES) {
  const path = join(ROOT, ADMIN, 'src', 'api', file);
  let text;
  try {
    text = readFileSync(path, 'utf8');
  } catch {
    console.log(`index source missing (skipped): ${file}`);
    continue;
  }
  const stmts = [];
  for (const raw of splitSql(text)) {
    const one = raw.replace(/\s+/g, ' ').replace(/;+\s*$/, '').trim();
    if (!KEEP.test(one) || SKIP_STMT.test(one)) { pruned++; continue; }
    const table = stmtTable(one);
    if (table && !provisioned.has(table)) { prunedTable++; continue; }
    let patched = one;
    if (/^(create\s+(unique\s+)?index)/i.test(patched) && !/if\s+not\s+exists/i.test(patched)) {
      patched = patched.replace(/^(create\s+)(unique\s+)?(index\s+)(concurrently\s+)?/i, '$1$2$3$4if not exists ');
    }
    if (/^create\s+policy/i.test(patched)) {
      const m = patched.match(/create\s+policy\s+("?)([\w -]+)\1\s+on\s+([\w".]+)/i);
      if (m) {
        const drop = `drop policy if exists ${m[1]}${m[2]}${m[1]} on ${m[3]}`;
        // Only add the guard when the source script did not already drop it.
        if (!seenStmt.has(drop.toLowerCase())) patched = drop + ';\n' + patched;
      }
    }
    const key = patched.toLowerCase();
    if (seenStmt.has(key)) { pruned++; continue; }
    seenStmt.add(key);
    stmts.push(patched + ';');
    kept++;
  }
  if (stmts.length) {
    for (const st of stmts) stmtList.push({ file, sql: st.replace(/;+\s*$/, '') });
  }
}
// Every statement is executed through a throwaway helper that reports and
// swallows failures, so this file is safe to paste AFTER the tables exist (it
// skips instead of aborting the run) and safe to re-paste afterwards. Each
// statement is additive, so nothing is lost by running it twice.
idx.push(`-- ---- guarded execution ----`);
idx.push(`${TRY}() runs one statement and only reports a failure, so the order`);
idx.push(`these files are pasted in never matters and a re-run is harmless.`);
idx.push(`create or replace function ${TRY}(p_sql text) returns void language plpgsql as $fn$`);
idx.push(`begin`);
idx.push(`  execute p_sql;`);
idx.push(`exception when others then`);
idx.push(`  raise notice 'bluebell 00_indexes: skipped % (%)', left(p_sql, 70), sqlerrm;`);
idx.push(`end`);
idx.push(`$fn$;`);
idx.push(``);
let lastFile = null;
for (const { file, sql } of stmtList) {
  if (file !== lastFile) {
    idx.push(`-- from src/api/${file}`);
    lastFile = file;
  }
  idx.push(`select ${TRY}($q$${sql}$q$);`);
}
idx.push(``);
idx.push(`drop function ${TRY}(text);`);
idx.push(``);
idx.push(`-- ${kept} statement(s) kept, ${pruned} pruned as already-applied or non-additive,`);
idx.push(`-- ${prunedTable} pruned because their table is not part of Bluebell's provisioned set.`);

// ----------------------------------------------- tools/export-exact-ddl.sql
const exportDdl = `-- export-exact-ddl.sql — READ ONLY. Run this in the JMIS Supabase SQL
-- Editor (project ${jmisUrl.replace(/^https:\/\//, '')}) and paste the single
-- text result into bluebell/db/01_schema_exact.sql, then re-run
-- tools/gen-schema.mjs with --use-exact to replace the generated DDL with the
-- byte-exact definition (defaults, indexes, constraints and all).
--
-- It never writes: SELECT only, from the catalog. The relname list below uses
-- the JMIS-side names (jmis_*), which are also the names Bluebell provisions.
select
  'create table ' || quote_ident(c.relname) || ' (' || E'\n' ||
  string_agg(
    '  ' || quote_ident(a.attname) || ' ' ||
    format_type(a.atttypid, a.atttypmod) ||
    case when a.attnotnull then ' not null' else '' end ||
    coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), ''),
    ',' || E'\n'
    order by a.attnum
  ) || E'\n);' || E'\n' ||
  coalesce(
    E'\n-- indexes\n' ||
    string_agg(distinct pg_get_indexdef(i.indexrelid) || ';', E'\n'),
    ''
  ) || E'\n' ||
  coalesce(
    E'\n-- constraints\n' ||
    (
      select string_agg(con.def || ';', E'\n')
      from pg_constraint con
      where con.conrelid = c.oid
    ),
    ''
  ) || E'\n' ||
  coalesce(
    E'\n-- rls\n' ||
    case when c.relrowsecurity then 'alter table ' || quote_ident(c.relname) || ' enable row level security;' else '' end ||
    E'\n' ||
    (
      select string_agg(
        'drop policy if exists ' || quote_ident(s.polname) || ' on ' || quote_ident(c.relname) || ';' || E'\n' ||
        'create policy ' || quote_ident(s.polname) || ' on ' || quote_ident(c.relname) || ' ' ||
        case s.polcmd
          when 'r' then 'for select'
          when 'a' then 'for insert'
          when 'u' then 'for update'
          when 'd' then 'for delete'
          else 'for all'
        end || ' to ' ||
        array_to_string(array(select pg_get_userfromuids(x) from unnest(s.polroles) x), ', ') || ' ' ||
        coalesce('using (' || pg_get_expr(s.polqual, s.polrelid) || ')', '') || ' ' ||
        coalesce('with check (' || pg_get_expr(s.polwithcheck, s.polrelid) || ')', '') || ';',
        E'\n'
      )
      from pg_policies p
      join pg_policy s on s.polname = p.policyname
      where p.tablename = c.relname
    ),
    ''
  ) as ddl
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
left join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
left join pg_index x on x.indrelid = c.oid
left join pg_class i on i.oid = x.indexrelid
where n.nspname = 'public'
  and c.relkind = 'r'
  and c.relname in (${toProvision.map((t) => `'${(catalogOf.get(t) || t).replace(/'/g, "''")}'`).join(', ')})
group by c.oid, c.relname, c.relrowsecurity
order by c.relname;
`;

// ------------------------------------------------------------------- write
const body = {
  'db/01_schema.sql': schema.join('\n') + '\n',
  'db/02_rls.sql': rls.join('\n') + '\n',
  'db/00_indexes.sql': idx.join('\n') + '\n',
  'db/03_storage.sql': sto.join('\n') + '\n',
  'db/04_seed_bluebell.sql': seed.join('\n') + '\n',
};
const ORDER = ['db/01_schema.sql', 'db/02_rls.sql', 'db/00_indexes.sql', 'db/03_storage.sql', 'db/04_seed_bluebell.sql'];

// db/apply_all.sql — the five, in paste order, one paste. The rename script JMIS
// has is deliberately NOT part of Bluebell: jmis_* names are kept, and renaming
// would destroy another school's tables if this ever touched a shared project.
const applyAll = [
  `-- apply_all.sql — Bluebell's provisioning bundle in paste order (01, 02, 00, 03, 04),`,
  `-- one paste. Bluebell keeps JMIS's jmis_* table names and runs in its OWN project,`,
  `-- so there is no rename step. Remaining placeholders are listed below; supply them`,
  `-- in tools/site-content.json and re-run the generator, or edit the row afterwards.`,
  `-- ${STAMP}`,
  ``,
];
for (const rel of ORDER) {
  applyAll.push(`-- >>>>>>>>>> ${rel}`);
  applyAll.push(body[rel].replace(/\s+$/, ''));
  applyAll.push(``);
}

const files = {
  ...body,
  'db/apply_all.sql': applyAll.join('\n') + '\n',
  'tools/export-exact-ddl.sql': exportDdl,
  'db/README.md': readme({ toProvision, phantom, skipped, buckets, project: bluebellProject }),
};

function readme({ toProvision, phantom, skipped, buckets, project }) {
  return `# Bluebell provisioning bundle

${STAMP}

Bluebell keeps JMIS's \`jmis_*\` table names verbatim (brand.json \`renameTables=false\`)
and runs in its **own** Supabase project, so there is no rename step and no shared-
database hazard. Regenerate after any JMIS schema change:

    node tools/gen-schema.mjs

Paste into **Bluebell's** Supabase SQL Editor (project \`${project}\`) in this order,
one file at a time — or paste \`apply_all.sql\` on its own:

| order | file | what it does |
|---|---|---|
| 1 | \`01_schema.sql\` | \`CREATE TABLE IF NOT EXISTS\` for ${toProvision.length} tables, exact JMIS columns/types, PKs, deferred FKs |
| 2 | \`02_rls.sql\` | enables RLS + permissive \`anon\`/\`authenticated\` policies |
| 3 | \`00_indexes.sql\` | indexes/policies authored in \`${ADMIN}/src/api/*.sql\`, replayed through \`${TRY}()\`; needs the tables from step 1, so it is pasted after them |
| 4 | \`03_storage.sql\` | public buckets (${buckets.join(', ')}) + storage policies |
| 5 | \`04_seed_bluebell.sql\` | the single \`${SETTINGS}\` row + first admin grant |

\`${TRY}()\` reports and skips a statement that does not apply instead of aborting the
batch, so one bad statement cannot block the rest - but that also means pasting
\`00_indexes.sql\` before the tables exist would quietly create no indexes at all.
With a Supabase personal access token the same order is applied automatically:
\`node tools/run-sql.mjs --apply\`.

Nothing in the bundle is destructive: every statement is \`IF NOT EXISTS\`,
\`DROP POLICY IF EXISTS\`-guarded or \`NOT VALID\`-deferred, so the whole set can be
re-pasted after a change.

## Placeholders

Bluebell's real school values are unknown at clone time and are emitted as
\`BLUEBELL_*_PLACEHOLDER\`. Fill them in \`tools/site-content.json\` (settings +
contact/about copy) and re-run this generator, or edit the \`${SETTINGS}\` row through
the admin Setting page afterwards. Run \`grep -rn "BLUEBELL_.*PLACEHOLDER" db\` to
list whatever remains.

## Coverage

* **Referenced and provisioned (${toProvision.length}):** ${toProvision.join(', ')}
* **Referenced by the code but absent from the JMIS catalog (${phantom.length}):** ${phantom.length ? phantom.join(', ') : 'none'} — not provisioned. JMIS does not have them either, so Bluebell behaves exactly like JMIS on those callsites (fail-soft reads, silently-dropped writes). Any that a repo setup script does create are handled by \`00_indexes.sql\`, pasted once the tables exist.
* **Present in JMIS but not used by the clone (${skipped.length}), deliberately skipped:** ${skipped.join(', ') || 'none'} — the clone would only create them if its code called them.

## Upgrading to byte-exact DDL

The catalog carries columns, types, nullability, primary keys and foreign keys,
but **not** defaults, indexes or hand-written policies. \`tools/export-exact-ddl.sql\`
is a read-only query to run in the **JMIS** editor that prints the exact
\`CREATE TABLE\`/\`pg_get_indexdef\`/\`pg_constraint\`/\`pg_policies\` text for the same
table set; paste the result into \`db/01_schema_exact.sql\` if you ever need the
generated bundle replaced with the literal JMIS definition.
`;
}

if (DRY) {
  for (const [rel, text] of Object.entries(files)) console.log(`--dry ${rel} (${text.length} B)`);
} else {
  mkdirSync(DB, { recursive: true });
  for (const [rel, text] of Object.entries(files)) {
    writeFileSync(join(ROOT, rel), text.replace(/\n/g, '\r\n'), 'utf8');
    console.log(`wrote ${rel} (${text.split('\n').length} lines)`);
  }
}
if (typeNotes.length) console.log(`columns with no PostgREST format (emitted as text): \n  ${typeNotes.join('\n  ')}`);
